// The ambient world actors -- LEGO Loco's townspeople/animals and its road traffic.
//
// Two leaf classes over one shared base, distinguished purely by the TileKind CATEGORY of the
// kind id they were spawned from (`TileKind::TileKind_GetCategory(kindId)`, 0x446030, which is
// just `(kindId >> 10) & 0xff` -- see docs/TILEKIND_IDS.md, generated by tools/resstrings.py):
//
//   category 7  (ids 0x1c00-0x1fff)  people\* + animals\*   -> WalkerActor      (0xf4 bytes)
//   category 8  (ids 0x2000-0x23ff)  vehicles\*             -> RoadVehicleActor (0xf0 bytes)
//
// The single factory is DecorObjMgrMaybe::SpawnActorForKindMaybe (0x4349d0), which branches on
// that category and returns 0 for every other one. Both are spawned by a placed building
// (FUN_00458430) from its kind descriptor's own 5-entry candidate table
// (BigObj::aPossibleMinifigs, +0x524 -- src/CursorDesc.h), under a global population cap
// of nActiveCategory7Maybe + nActiveCategory8Maybe < 100.
//
// ⚠ These were catalogued for many sessions as `NetMsgPayload7`/`NetMsgPayload8`, "clone wire
// records into per-participant/roster objects". That was REFUTED end-to-end in v388 -- nothing
// in either class touches the network stack -- and the classes were renamed to
// DecorActor7Maybe/DecorActor8Maybe, then to their present certain names in v389 once the
// resource-string table pinned the two categories to `people\`/`animals\` and `vehicles\`.
// Do not confuse the old name with GameNetMsgQueue.h's `NetMsgPayloadObjMaybe`, which is a
// DIFFERENT and still-valid (still unidentified) model of the queue's 0xe/0x10 payload case.
//
// Behaviour, shared by both leaves: pick a destination (nDestPos), resolve it to a tile on the
// actor's own network (paths\* / category 0xc for WalkerActor, roads\* / category 0xd for
// RoadVehicleActor), then step toward it one tile at a time, re-deciding at
// dwNextDecisionTickMaybe. WalkerActor additionally boards trains -- pRidingTrainMaybe -- which
// is the ONLY reason it is allowed onto a category-3 (track\*) tile.
#pragma once

#include "WidgetBase.h"   // AnimDescRefObj0x477488 -- the shared base at offset 0
#include "TilePlacedObj.h"

class PeerTrainNode;
struct PeerTrainNodePartial; // src/PeerTrainNode.h -- the real, modeled train node (same
                              // object as the never-defined `PeerTrainNode` handle type)
class TrackGraph;            // src/TrackGraph.h

// 0xf0/240 bytes; ctor 0x433a20, dtor 0x433be0, vtable 0x477f18 (22 slots: 15 inherited from
// the AnimDescRefObj0x477488 chain plus 7 of its own, two of which are PURE -- slots 16 and 18
// both point at the shared __amsg_exit(0x19) purecall stub at 0x467e90).
//
// Its only two ctor callers are the two leaf ctors below; that xref pair is what pins the
// hierarchy.
class DecorActorBase : public AnimDescRefObj0x477488 {
public:
    // +0x88 -- 0..7, ctor sets 4 (and BOTH leaf ctors immediately re-set it to 4). Rises by 1
    // on arriving at a scheduled destination or boarding a train, by 2 on completing a wander,
    // and decays by 1 for every 180 idle ticks (TickMaybe). Reads as a
    // satisfaction/mood meter; the consumer that renders it has not been read yet, hence Maybe.
    unsigned char nMoodMaybe;
    bool bSuspendedMaybe;      // +0x89 -- set, every leaf TickMaybe returns immediately
    // +0x8a -- copied by the slot-9 copy constructor, never written anywhere else.
    // ⚠ +0x8b is NOT a member: it is compiler alignment padding ahead of the pointer below,
    // and it must stay UNDECLARED. The header carried an explicit `pad0x8b` until 2026-07-27,
    // which is layout-identical but NOT copy-identical -- an explicit pad byte is a real
    // member, so the implicit copy constructor copies it. src/Obj0x477798Family.cpp's
    // WalkerRegistryMaybe::SetCopyAtMaybe (0x435700), which inlines that copy constructor
    // whole, is the oracle: the original walks +0x8a straight to +0x8c. Same for +0xe5 below.
    unsigned char Unk0x8a;
    // +0x8c/+0x90 -- the two buildings this actor is attached to. FUN_00434040 picks between them
    // as scheduled destinations by running the current wall-clock time (via _localtime) against
    // the destination's kind descriptor's two shift-time sub-objects (+0x534/+0x548,
    // src/CursorDesc.h):
    //   pOwnerObjMaybe's shift IS active now       -> state 2, head there, then stay 0xe10 ticks
    //   pSpawnerObjMaybe's shift is NOT active     -> state 1, head there
    //   otherwise                                  -> state 3, wander to a random category-2
    //                                                 (building\*) object
    //
    // WHICH IS WHICH, resolved 2026-07-26 by enumerating every writer of the two offsets across
    // the whole .text (the earlier note here guessed "pOwnerObjMaybe is the building that spawned
    // this actor", and that was wrong -- it conflated the two):
    //   +0x8c is written by EXACTLY ONE site in the binary, DecorObjMgrMaybe::
    //   SpawnActorForKindMaybe (0x4349d0), from the `pOwner` argument its caller
    //   TilePlacedObj::SpawnOwnedActorMaybe passes as `this`. So it is the building that
    //   PHYSICALLY SPAWNED the actor, stamped once at construction and never changed -- hence
    //   pSpawnerObjMaybe. (Renamed from pScheduleAwayObjMaybe; audited per CLAUDE.md, all 817
    //   COMDATs across 75 objs byte-identical before/after.)
    //   +0x90 is written by EXACTLY ONE site too, DecorActorBase::ActivateMaybe (0x433ca0), which
    //   scans the world for a category-2 building that still has room (its own
    //   bSpawnedActorCountMaybe below the descriptor's bMaxEmployees/+0x516) AND whose
    //   descriptor's 5-entry kind list at +0x518 names this actor's own kind -- then registers
    //   `this` into that building's apSpawnedActorMaybe and stores it here. So it is the
    //   WORKPLACE the actor applied to and got accepted by, which is also why the dtor (and
    //   ActivateMaybe's own re-entry path) unregisters from THIS one and not from the spawner.
    // The names are kept `Maybe` because "spawn origin" vs "home" is still a guess for +0x8c --
    // what is now certain is that the two are different roles and which writer owns each.
    TilePlacedObj *pSpawnerObjMaybe;      // +0x8c
    TilePlacedObj *pOwnerObjMaybe;        // +0x90
    unsigned int dwSpawnTickMaybe;        // +0x94 -- g_dwGameTick at construction
    // +0x98/+0x9c -- this actor's PUBLISHED trail anchor: a hotspot position it re-snapshots
    // every time nTrailAnchorCounterMaybe passes 10 moving ticks. CORRECTED 2026-07-26 (v390
    // called this "stuck detection", which only accounted for the writer): the READER is
    // WalkerActor::FollowLeaderStepMaybe, which steps THIS actor toward the trail anchor of a
    // DIFFERENT actor -- the next entry in DecorObjMgrMaybe's registry, handed to every
    // TickMaybe as its argument. So the pair is a crowd-following breadcrumb, and it is what
    // makes the population throttle (DecorObjMgrMaybe::bThrottleMaybe) cheap: under load the
    // actors form conga lines instead of each running a full path search. -1/-1 means "no
    // anchor published yet", and a follower seeing that just re-poses itself instead.
    int nTrailAnchorPosXMaybe;
    int nTrailAnchorPosYMaybe;
    unsigned int dwNextDecisionTickMaybe; // +0xa0 -- re-decide once g_dwGameTick passes this
    unsigned int dwLastRetargetTickMaybe; // +0xa4 -- g_dwGameTick at the last retarget; 0 while
                                          //   idle, which is what arms TickMaybe
    // +0xa8 -- final destination, world pixels (-1/-1 = none). Modeled as a POINT rather than
    // two ints because RoadVehicleActor::ChooseNextStepTileMaybe passes its ADDRESS to
    // ApplyLaneOffsetMaybe, which reads and writes both halves through one pointer.
    POINT ptDestMaybe;
    int nNetEntryPosXMaybe; // +0xb0 -- nearest tile of the actor's own network, used to get
    int nNetEntryPosYMaybe; // +0xb4    back onto it when standing off-network
    POINT ptDestTileMaybe;  // +0xb8 -- the destination resolved onto a network tile; a POINT
                            //   for the same reason as ptDestMaybe above
    int nDestGraphNodeIdMaybe; // +0xc0 -- that tile's TilePlacedObj::nGraphNodeIdMaybe, or 0xff
    int nPrevDestPosXMaybe; // +0xc4 -- previous destination, so a re-roll can avoid repeating it
    int nPrevDestPosYMaybe; // +0xc8
    POINT ptStepMaybe;      // +0xcc -- the next single step's target, world pixels; a POINT for
                            //   the same reason as ptDestMaybe above
    int nStepDeltaXMaybe;   // +0xd4 -- (step - current), recomputed by FUN_00433dc0
    int nStepDeltaYMaybe;   // +0xd8
    int nStepDistanceMaybe; // +0xdc -- remaining distance to the step target; 0 == not moving,
                            //   and that is exactly what every TickMaybe tests to decide
                            //   between "keep walking" and "pick a new destination"
    unsigned int nTrailAnchorCounterMaybe; // +0xe0 -- moving ticks since the last trail-anchor
                                           //   snapshot; both steppers reset it past 10
    unsigned char nSubTickCounterMaybe; // +0xe4 -- wraps at 3; the actors only move on every
                                        //   third tick, which is their speed divider.
                                        //   +0xe5..+0xe7 is alignment padding and stays
                                        //   UNDECLARED -- see the +0x8b note above.
    int nScheduleStateMaybe; // +0xe8 -- FUN_00434040's last verdict (1/2/3), replayed by
                             //   FUN_00434100 when the actor arrives. THE LAST MEMBER: this
                             //   class ends at 0xec, and the +0xec int each leaf carries is
                             //   the LEAF's own first member, not this class's. Pinned
                             //   2026-07-27 -- see the Unk0xec note on WalkerActor below.

    DecorActorBase(int kindId);
    virtual ~DecorActorBase();

    // --- ordinary (non-virtual) members, all shared by both leaves ------------------------
    // 0x433dc0 -- the movement primitive. Recomputes nStepDelta{X,Y} as
    // (target - hotspot) and nStepDistanceMaybe as their length, then RETURNS the position to
    // move to: rect.left/top advanced toward the target by at most nMaxStep on each axis. A
    // (-1,-1) target means "stop": it zeroes all three fields and returns the current hotspot
    // position unchanged. The 8-byte by-value POINT return is why Ghidra renders this
    // `void f(int *retbuf, ...)` -- that leading pointer is MSVC's hidden return buffer.
    POINT ComputeStepTargetMaybe(int nTargetX, int nTargetY, int nMaxStep);
    // 0x433ec0 -- the tile of the given kind CATEGORY under this actor's own sprite
    // footprint, or NULL. Probes up to three sample points (an extra leading one only when
    // this actor is itself category 8, i.e. a RoadVehicleActor) and returns the first hit.
    TilePlacedObj *FindFootprintTileOfCategoryMaybe(unsigned short nCategory, int x, int y);
    // 0x434040 -- runs the wall clock (via localtime) against the two scheduled destinations'
    // shift windows and returns the verdict 1/2/3 documented on pSpawnerObjMaybe above, or 0
    // for "not yet" (the deadline has not passed, or the player is dragging us).
    int ChooseScheduleStateMaybe(unsigned int dwTick);
    // 0x434100 -- the arrival handler: replays the verdict ChooseScheduleStateMaybe last
    // returned now that the actor has reached nDestPos, then drops the destination. Returns 0
    // when it declined to run (hidden, or being dragged); both callers ignore the result.
    unsigned char OnArriveAtDestinationMaybe(int nScheduleState);

    // ⛔ 0x4344a0, 82 B -- VTABLE SLOT 13 (+0x34), this class's override of
    // AnimDescRefObj0x477488::SetCategoryIfPrintable. BODY FULLY READ AND VERIFIED EXACT
    // (2026-07-31, v537, MATCH on the first compile), then WITHHELD at a measured -1524 B:
    //
    //     void DecorActorBase::SetCategoryIfPrintable(char *pszName) {
    //         AnimDescRefObj0x477488::SetCategoryIfPrintable(pszName);
    //         if (GetActorCategoryMaybe(this) == 7) {
    //             DecorObjMgrMaybe_00485448.TickCategory7OnlyMaybe();
    //         }
    //         if (_stricmp(pszName, "PARTY") == 0) {
    //             DecorObjMgrMaybe_00485448.bThrottleMaybe = true;
    //             DecorObjMgrMaybe_00485448.dwLastTickMaybe = g_dwGameTick;
    //         }
    //     }
    //
    // It is the OUT-OF-LINE copy of the exact three-statement block this class's own ctor
    // (0x433a20) inlines at its `pKind->szCategoryName[0] != 0` arm -- same calls, same order,
    // same "PARTY" literal (read from the image bytes at 0x47e4fc, not from a Ghidra s_ label).
    // Landing it needs a DECLARATION on this class, and that one declaration costs
    // WorldBoardMaybe::FindNearestObjOfCategoryMaybe (0x457ce0) -951, WorldBoardMaybe_
    // ResetAllTilesMaybe -211 and src/RoadVehicleActor.cpp -504, against +82 here and +60 in
    // src/TilePlacedObj.cpp. Bisected to the declaration alone: reverting src/WidgetBase.h to the
    // split model below and keeping ONLY this declaration still costs the full -1524.
    //
    // ⭐ WHAT READING IT SETTLED, which outlives the withholding: slot 13 is
    // SetCategoryIfPrintable. src/WidgetBase.h models that ONE function as TWO -- a declared-only
    // `_v13()` placeholder for the slot AND a separate non-virtual `SetCategoryIfPrintable` for
    // 0x405e20 -- which is exactly CLAUDE.md's "a vtable slot and a named method at the same
    // address are ONE function" hazard, caught in the wild a second time (v477's CarNetObj was
    // the first). All three actor-family vtables (0x477eb8, 0x477f18, 0x4780b8) carry 0x4344a0 at
    // +0x34 where the two non-actor tables (0x477488, 0x4784c8) carry 0x405e20. Nothing objected
    // for so long because every caller of the base spelling is a CONSTRUCTOR (TilePlacedObj's
    // 0x4580a0, this class's 0x433a20) and MSVC emits a direct `call 0x405e20` for a virtual
    // called from inside one, so both models produce identical bytes.
    // ⚖ UNIFYING THE TWO IS ALSO NET-NEGATIVE, -1005 B, and THREE compensating currencies were
    // measured and refuted -- do NOT re-run any of them:
    //   * src/Obj0x477798Family.h's `_v15`: restores its own TU (+152), costs RoadVehicleActor
    //     -504, leaves 0x457ce0's -951 untouched (correcting that header's own v486 note, which
    //     claimed the two headers were interchangeable currencies -- they are not);
    //   * AnimDescRefObj0x477488::EnsureSoundPlayingMaybe (0x405ab0): RoadVehicleActor -504,
    //     PlacedObjRegistryMaybe -152, WidgetBase.cpp -407, still no 0x457ce0;
    //   * that class's genuinely-missing slot 15 (0x4062a0): needs `class DecorActorBase;`
    //     forward-declared in src/WidgetBase.h to spell the return type TilePlacedObj's override
    //     already uses, and that forward declaration is itself a -6174 B lever across nine TUs.
    //     A `void *` return is not an escape -- it makes TilePlacedObj's override a return-type
    //     mismatch, which is an error, not a covariance.

    // NOT declared: DecorActorBase::BlitAnimFrameMaybe, slot 11 (+0x2c), 0x4343b0 -- this class's
    // own override of AnimDescRefObj0x477488's slot 11, empty apart from chaining the base. All
    // three actor vtables (0x477eb8, 0x477f18, 0x4780b8) carry 0x4343b0 at +0x2c where the two
    // non-actor tables carry the base's 0x405e60, so the override is real and it belongs here.
    //
    // ⚠ THE DIAL IS PRICED, not suspected -- v539 transcribed it, put the declaration in, and
    // measured the full per-file table: src/WorldBoardMaybe.cpp's 0x457ce0 loses its whole 951 B
    // and src/RoadVehicleActor.cpp 504 B, against 50 B for the function itself and a 60 B
    // consolation in src/TilePlacedObj.cpp -- net -1345 B. Same two victims this header's
    // GetActorCategoryMaybe note above already documents. The body lives on a TU-local view struct
    // in src/DecorActor.cpp instead (the TrackTileObjChannelView0x44b130 precedent), which costs
    // nothing here. Do not "just try it" again -- it has been tried and it is 1345 B.

    // --- this class's own vtable slots, 15..21 -------------------------------------------
    // slot 15 (+0x3c) -- overridden by BOTH leaves, which each call this base body first,
    // forwarding their own argument. The base body IGNORES it (its `ret 4` is the only
    // evidence the parameter exists at all -- Ghidra renders this function 0-param). The
    // argument is the NEXT actor in DecorObjMgrMaybe's own registry: its tick loop calls
    // `pPrev->TickMaybe(pCur)` walking the list pairwise, which is how an actor gets at a
    // neighbour's published trail anchor without the registry being visible to it.
    virtual void TickMaybe(DecorActorBase *pNextActor);
    // slot 16 (+0x40) -- PURE in the base. WalkerActor::SetDestinationTileMaybe (0x432940).
    virtual void SetDestinationTileMaybe(int x, int y) = 0;
    // slot 17 (+0x44) -- 0x434260, shared by both leaves. Takes the object to head for;
    // TickMaybe passes 0 to mean "no target, go idle".
    virtual void HeadForObjectMaybe(TilePlacedObj *pTarget);
    // slot 18 (+0x48) -- PURE in the base. WalkerActor::ChooseNextStepTileMaybe (0x432ae0).
    virtual void ChooseNextStepTileMaybe(int x, int y) = 0;
    // slot 19 (+0x4c) -- 0x4343f0, shared by both leaves. Given a graph and a node id, picks
    // a replacement destination node (WalkerActor::ChooseNextStepTileMaybe calls it when
    // GetStepDirectionMaybe reports the current destination unreachable).
    virtual int PickReachableDestNodeMaybe(TrackGraph *pGraph, int nFromNodeId);
    // slot 20 (+0x50) -- the "activate" entry point DecorObjMgrMaybe::
    // ActivateEligibleEntriesMaybe calls on eligible registry entries.
    virtual void ActivateMaybe();
    // slot 21 (+0x54) -- the "may I stand at this world position" test; overridden by both
    // leaves (WalkerActor::CanStandAtMaybe 0x433860, RoadVehicleActor 0x454050).
    virtual unsigned char CanStandAtMaybe(int x, int y);
};

// 0xf4/244 bytes; ctor 0x4326f0, dtor 0x432740, vtable 0x477eb8 (24 slots -- adds 2 of its own
// past the base's 22). TileKind category 7: every `people\*` and `animals\*` kind.
//
// Walks the paths\* network (category 0xc). Its destinations are random category-2 building\*
// objects, picked via PickRandomBigObjByCategory. It is the only actor that can board a train.
class WalkerActor : public DecorActorBase {
public:
    // +0xec -- copied by the slot-9 copy constructor, never written anywhere else.
    //
    // It belongs to THIS class rather than to DecorActorBase, and the copy constructor is what
    // says so. Inlined whole into WalkerRegistryMaybe::SetCopyAtMaybe (0x435700,
    // src/Obj0x477798Family.cpp), it emits each base's vptr store at the END of that base's own
    // member copies -- 0x477820 after +0x20, 0x477488 after +0x86, 0x477f18 after +0xe8 and
    // 0x477eb8 after +0xf0. The 0x477f18 store landing BETWEEN the +0xe8 and +0xec copies puts
    // the boundary at 0xec, so DecorActorBase is 0xec bytes and this int opens the leaf.
    // RoadVehicleActor carries the same field for the same reason (its own 0x4780b8 store comes
    // after +0xec, which is why that class is 0xf0 and not the "no members of its own" it was
    // documented as). Declared in DecorActorBase until 2026-07-27; the two spellings are
    // layout-identical, so only the copy constructor could ever have told them apart.
    int Unk0xec;
    // +0xf0 -- the PeerTrainNode this actor has boarded, 0 when on foot. Set by
    // BoardTrainMaybe, which claims the first free slot in the train's own 8-entry passenger
    // array (PeerTrainNodePartial::apPassengerMaybe, +0x38); cleared by LeaveTrainMaybe, which
    // the dtor also calls so a deleted passenger does not leave a dangling slot behind. While
    // non-0 the actor is additionally allowed onto category-3 (track\*) tiles -- see
    // ChooseNextStepTileMaybe's tile-kind test.
    PeerTrainNode *pRidingTrainMaybe;

    WalkerActor(int kindId);
    virtual ~WalkerActor();

    // --- ordinary (non-virtual) members, all in src/WalkerActor.cpp -----------------------
    // 0x433160 -- picks the standing/idle sprite subframe from nMoodMaybe: 5 when the mood is
    // 0, 6 below 3, 4 below 5, else 7. Only ever changes it when it differs.
    void UpdateIdlePoseFromMoodMaybe();
    // 0x4331b0 -- picks the WALKING sprite subframe from the dominant axis of
    // nStepDelta{X,Y}: on a mostly-horizontal step 0 for left / 2 for right, otherwise 3 for
    // up / 1 for down.
    void UpdateFacingFromStepDeltaMaybe();
    // 0x433370 -- the track-tile gate: what to do about the track\* tile at (x, y).
    unsigned char TryEnterTrackTileMaybe(int x, int y);
    // 0x433530 -- board pTrain (0 == get off whatever we are on).
    unsigned char BoardTrainMaybe(PeerTrainNodePartial *pTrain);
    // 0x4336a0 -- step off the train: clear this actor out of pRidingTrainMaybe's own
    // passenger array, null the field, and place it back down beside the track.
    void LeaveTrainMaybe();

    virtual void TickMaybe(DecorActorBase *pNextActor); // slot 15 -- 0x4327b0
    virtual void SetDestinationTileMaybe(int x, int y); // slot 16 -- 0x432940
    virtual void ChooseNextStepTileMaybe(int x, int y); // slot 18 -- 0x432ae0
    virtual unsigned char CanStandAtMaybe(int x, int y); // slot 21 -- 0x433860
    // slots 22/23 -- this class's own two NEW slots, past the base's 22. Both are steppers
    // its own TickMaybe dispatches virtually rather than calling directly, and neither is
    // overridden anywhere, so the indirection is only ever self-dispatch.
    // 0x432fd0 -- one movement sub-step: aboard a train, ride along with it (and get off on
    // arrival); on foot, advance toward nStepPos at the kind's own speed. Returns the
    // remaining nStepDistanceMaybe, which its caller tests for 0 ("arrived").
    virtual int AdvanceMovementMaybe();
    // 0x433220 -- the population-throttle stepper: step toward pLeader's published trail
    // anchor instead of doing any path work of our own. Also returns nStepDistanceMaybe.
    virtual int FollowLeaderStepMaybe(DecorActorBase *pLeader);
};

// 0xf0/240 bytes; ctor 0x4533d0, dtor 0x4533f0, vtable 0x4780b8 (29 slots -- adds 7 of its own).
// TileKind category 8: every `vehicles\*` kind (van, ferrari, milkflot, ferr2, engine).
// Adds no data members at all past DecorActorBase.
//
// Drives the roads\* network (category 0xd); its destination is a placed instance of a randomly
// chosen road kind id (`0x3400 + rand() % 0x29` -- exactly the 41 road kinds in
// docs/TILEKIND_IDS.md's category 0xd), and it is placed on its owner's tile at spawn with no
// randomisation and no activate call, unlike WalkerActor.
class RoadVehicleActor : public DecorActorBase {
public:
    // +0xec -- this class's ONLY data member, and the twin of WalkerActor::Unk0xec above (see
    // that note for how the copy constructor pins it to the leaf rather than to the base).
    int Unk0xec;

    RoadVehicleActor(int kindId);
    virtual ~RoadVehicleActor();

    // --- ordinary (non-virtual) member, in src/RoadVehicleActor.cpp ------------------------
    // 0x453fb0 -- picks the driving sprite subframe from the SIGNS of nStepDelta{X,Y}: unlike
    // WalkerActor's 4-way dominant-axis test this is a full 8-way compass, and the eight even
    // subframes 0..14 are laid out W, SW, S, SE, E, NE, N, NW.
    void UpdateFacingFromStepDeltaMaybe();

    virtual void TickMaybe(DecorActorBase *pNextActor); // slot 15 -- 0x453450
    virtual void SetDestinationTileMaybe(int x, int y); // slot 16 -- 0x453570
    virtual void ChooseNextStepTileMaybe(int x, int y); // slot 18 -- 0x453790 (1499 bytes, the
                                        //   single largest unclaimed app-region function)
    virtual unsigned char CanStandAtMaybe(int x, int y); // slot 21 -- 0x454050
    // slots 22/23 -- this class's own two NEW slots past the base's 22, exactly like
    // WalkerActor's own pair (the two leaves' slot numbers coincide but the slots are
    // independent -- neither class overrides the other's).
    // 0x453eb0 -- one movement sub-step. Moves first and asks questions after: it repositions
    // to the new step target, queries the manager for a pixel-accurate collision against every
    // other actor, and only keeps the move if that came back clear AND CanStandAtMaybe agrees.
    // Otherwise it puts itself back and, unless the collision code was 7, drops its target.
    virtual int AdvanceMovementMaybe();
    // 0x453d70 -- the road-lane offset table: nudge *pPos off the tile centre by a few pixels
    // according to the direction being driven IN and the direction being turned OUT to, so a
    // vehicle sits on the correct side of the road and cuts corners plausibly. Directions are
    // the same 0-3 the tile graph uses (0 = -x, 1 = +y, 2 = +x, 3 = -y, reverse == (d+2)&3);
    // 0xff means "no direction" and leaves the point alone, as does a (-1,-1) point. The
    // offsets encode LEFT-HAND traffic -- see the table in src/RoadVehicleActor.cpp.
    virtual void ApplyLaneOffsetMaybe(POINT *pPos, unsigned char nDirIn, unsigned char nDirOut);
};
