// NetSessionEventQueue (DAT_004a9990) -- a session/notification queue tied to
// network-game state. See docs/subsystems.md's own entry for the full cluster map; this TU
// now covers the whole cluster: the ctor/dtor pair (plus the compiler-synthesized
// scalar-deleting dtor), the 4-member "edge placement" quartet used to compute where a train
// hand-off connector tile lands on each of the board's 4 screen edges,
// PlaceEdgeLinksAndFlush, the Load/Save pair LoadLayoutAndPopulateBoard/SaveBoardLayout, and
// the BigObj-family registry pair BigObj_CreateAndInsert/BigObj_Remove. All are
// content-complete transcriptions; most remain PARKED (first-draft, not yet byte-matched) --
// see each function's own header comment/docs/PARKED.md for its specific residual.
//
// pEvents's ctor briefly stamps the shared Obj0x477798-family "generic reserve" vtable
// literal before finalizing to its own (0x477758) -- see docs/subsystems.md's "Obj0x477798
// 4-field collection family" entry (8 siblings, same field shape, each its own real vtable).
// Modeled 2026-07-21 as a REAL base/derived pair (retiring the earlier flattened manual
// `vtbl = g_vtable...` stamps and the VtblSlotProbe0x477758 this-casts): the two vtable-ptr
// writes the original emits in the ctor are just the compiler's own base-then-derived vtable
// stamping, and the dtor's re-stamp to 0x477798 is the base-dtor unwind.

#include <string.h>
#include <stddef.h>

#include "Pair16.h"
#include "DPlaySessionMgr.h"
#include "WidgetPicker.h"
#include "UIResources.h"
#include "TilePlacedObj.h"
#include "PeerTrainNode.h"
#include "PeerTrainSlotQueueMaybe.h" // g_PeerTrainSlotQueue singleton (DAT_004a98b0)
#include "WorldBoardMaybe.h"
#include "RandRange.h"
#include "EffectSpawner.h" // DAT_004fd220.EffectSpawner_SpawnAtPositionMaybe (canonical home)

#include "NetSessionEventQueue.h"

// FUNCTION: LOCO 0x41d250
// pEvents is constructed via a mem-initializer (not a body assignment) -- confirmed
// necessary: this class's own (compiler-automatic) vtbl store lands LAST, after pEvents
// is fully alive, matching CLAUDE.md's "mem-initializer schedules the vtable store last"
// rule; a body-assignment-style construction put the auto-store first instead (wrong).
// EFFECTIVE MATCH, DIFF 25/87: the only residual is the final `if (m_count == 0)` check --
// orig does an explicit `cmp eax,ebx` against the just-computed count even though the
// preceding `and eax,0xa` already sets the same flags; this compile reuses the `and`'s own
// flags directly (one fewer instruction). Tried `!m_count` in place of `== 0`: no effect,
// confirming a pure instruction-selection tie (same class as the quartet's own residuals).
NetSessionEventQueue::NetSessionEventQueue() : pEvents(10) {
    nPlacedObjectCount = 0;
}

// FUNCTION: LOCO 0x41d2d0
// EFFECTIVE MATCH, DIFF 5/55: the only residual is the compiler-automatic outer vtbl
// restamp landing right after (not right before) the pEvents.m_ptr read -- tried
// reordering the m_0c/m_ptr-read statements, zero effect either way, confirming a pure
// scheduling tie (same class as the ctor's own residual above). The body is empty on
// purpose: the original's whole teardown sequence (m_0c=0, the vtbl re-stamp to the
// 0x477798 base table, m_count=0, operator delete(m_ptr), m_ptr=0) is exactly the
// pEvents member's own derived-then-base dtor chain, modeled for real since 2026-07-21.
NetSessionEventQueue::~NetSessionEventQueue() {
}

// FUNCTION: LOCO 0x41d2b0 (??_GNetSessionEventQueue scalar dtor)
// Auto-generated by the virtual dtor above -- this COMDAT has no source line of its own.

// Minimal partial view of a queued category-3 BigObj-family item (TrackDepotTileObj/
// TrackConnectorTileObj's shared field layout -- see docs/subsystems.md's
// PlaceEdgeLinksAndFlush entry for the full field-identification writeup: both leaf types
// embed a 284-byte TrackTileObj base which itself embeds the 268-byte TilePlacedObj
// plain-object base, but the flush loop below only ever reads 3 fields generically through a
// raw item pointer, so the full class hierarchy is modeled here only as far as those 3 offsets
// -- the BigObj/TilePlacedObj families themselves stay deliberately out of scope, see the
// BigObj-family deferral note above).
struct BigObjCategoryPartial {
    char pad0x8[8];
    unsigned char categoryByte; // +8 (BigObj's own descriptor category, shared by all 3
                                      // category-3 leaf types via TileKind_GetOrLoadDescriptor)
};

struct QueuedBigObjItemPartial {
    char pad0x40[0x40];
    void *pKindDesc;            // +0x40 (AnimDescRefObj0x477488::pKindDesc, a BigObj*)
    char pad0x44[0x10c - 0x44];
    unsigned int dwTrackState;  // +0x10c (TrackDepotTileObj's own field)
    char pad0x110[0x120 - 0x110];
    void *pOwningTrain;         // +0x120 (TrackDepotTileObj's own field)
};

// Minimal partial view of WorldBoardMaybe::WorldBoardMaybe_PlaceObjectMaybe's own return value
// (a TilePlacedObj*, full hierarchy out of scope -- see above). Only the fields/virtual
// slots LoadLayoutAndPopulateBoard's own object-placement loop touches are named.
// ALSO reused (per the already-established PeerTrainNodePartial::carSlots precedent) as a
// reinterpretation of a CarNetObj* wherever only its shared AnimDescRefObj0x477488 base fields
// or one of its own CarNetObj-specific tail fields are needed -- szCategoryName/
// nCarCategory below are ONLY meaningful through that reinterpretation (ground-truthed
// against Ghidra's own real CarNetObj struct: base@0/AnimDescRefObj0x477488,
// nCarCategory@0x42c), never through a genuine TilePlacedObj* pointer.
struct TilePlacedObjPartial {
    // The virtual slots this partial's consumers dispatch through (declared-only; the
    // compiler's vtable ptr at +0 replaces 4 of the old pad0x0 bytes). ScalarDelete =
    // vtbl+0 (the standard scalar-deleting-dtor shape); InvokeArgAMaybe = vtbl+0x1c (slot 7);
    // ApplyRecordBlobMaybe = vtbl+0x34 (slot 13); GetOrAllocCarSlot = vtbl+0x3c (slot 15).
    virtual void ScalarDelete(unsigned int bFreeMemory);
    virtual void *_v01(); virtual void *_v02(); virtual void *_v03();
    virtual void *_v04(); virtual void *_v05(); virtual void *_v06();
    virtual void InvokeArgAMaybe(unsigned int arg);
    virtual void *_v08(); virtual void *_v09(); virtual void *_v10();
    virtual void *_v11(); virtual void *_v12();
    virtual void ApplyRecordBlobMaybe(void *pBlob);
    virtual void *_v14();
    virtual void *GetOrAllocCarSlot(unsigned short wKindId);

    char pad0x0[4];
    int nPosX;              // +0x8 (BigObj_Remove's own effect-spawn-position calc:
                                   // this + a BigObj-descriptor-derived half-width)
    int nPosY;              // +0xc (same calc, half-height)
    char pad0x10[0x18 - 0x10];
    unsigned char bValid;   // +0x18 (RectFlagObj0x477820::bValid, inherited via the
                                  // AnimDescRefObj0x477488 base chain -- doubles as a
                                  // just-constructed "did init succeed" flag, see
                                  // BigObj_CreateAndInsert)
    char pad0x19[0x40 - 0x19];
    void *pKindDesc;        // +0x40 (AnimDescRefObj0x477488::pKindDesc, a BigObj*; same
                                  // field/offset as QueuedBigObjItemPartial above)
    char pad0x44[0x7c - 0x44];
    char szCategoryName[12];  // +0x7c (AnimDescRefObj0x477488::szCategoryName, shared base
                                  // field -- see WidgetBase.h; car-pointer reinterpretation only)
    char pad0x88[0x94 - 0x88];
    unsigned int dwUnk0x94Maybe; // +0x94 (car-slot-family use only: written from the matching
                                  // CarSlotRecord::dwUnkMaybe -- a DIFFERENT field from
                                  // dwPlacementArgB below despite the same probe type; the two
                                  // never apply to the same real instance)
    char pad0x98[0xbc - 0x98];
    unsigned int dwPlacementArgB;   // +0xbc, set from the placement record's own dwArgBMaybe
    unsigned char Unk0xc0Maybe;  // +0xc0, zeroed on successful edge-tile placement
    char pad0xc1[0xc4 - 0xc1];
    unsigned int Unk0xc4Maybe;    // +0xc4
    unsigned int Unk0xc8Maybe;    // +0xc8
    unsigned int Unk0xccMaybe;    // +0xcc
    unsigned int Unk0xd0Maybe;    // +0xd0 (all 4 zeroed together by BigObj_Remove right
                                   // before flushing a neighbor tile's queued BigObj)
    char pad0xd4[0x42c - 0xd4];
    int nCarCategory;       // +0x42c (CarNetObj's own field, past the shared 136-byte
                                  // AnimDescRefObj0x477488 base and the CarNetState
                                  // sub-object; car-pointer reinterpretation only)
};

// BigObj's own resourceId (CursorDesc::resourceId, reached through BigObj's real
// Obj0x4779e0/CursorDesc base chain -- ground-truthed via Ghidra's get_struct_layout,
// not guesswork). Used generically wherever a TilePlacedObjPartial::pKindDesc /
// CarNetObj::pKindDesc pointer's own kind id is needed.
struct BigObjResourceIdPartial {
    char pad0x4[4];
    int resourceId; // +4
};

// The despawn "puff of smoke" effect spawner (0x423ab0) is dispatched through the canonical
// singleton in src/EffectSpawner.h (included above) -- this TU's local
// BigObjTrackingSetsMaybe view was retired v500 when 0x423ab0's definition landed in
// src/EffectSpawner.cpp (lint_alias: the local spelling aliased the now-defined address).
extern int DAT_00485234; // checked (twice, redundantly -- see BigObj_Remove) to pick the
                          // mobility flag passed to EffectSpawner_SpawnAtPositionMaybe

// WorldBoardMaybe (DAT_004aad08) -- shared canonical view in src/WorldBoardMaybe.h; this TU
// uses its wCols/wRows, bBoardDirtyNeedsRebuildFlag, and the tile-placement API.

// The backdrop descriptor (g_pBackdropDesc) -- the real CursorDesc, already fully modeled in
// src/CursorDesc.h (visible here transitively via TilePlacedObj.h). Only its own
// "%s%s.bmp"-built full bitmap path at +0x48 is needed here.
extern CursorDesc *g_pBackdropDesc; // DAT_004fd3c8

extern DPlaySessionMgr *g_pDPlaySessionMgr;
extern unsigned char DAT_004fd3dc;
extern char DAT_004aa8f8[];
extern char g_pInstallPathPrefix[]; // DAT_004a99c8

// CarSlotRecord/ObjectPlacementRecord/TrainPlacementRecord (the streamed savegame-layout
// records) now live in src/ThumbnailBmp.h -- they're ThumbnailBmp's own record format, and
// ThumbnailBmp.h is already transitively included here via WidgetPicker.h.

// A second partial view over the SAME real placed-tile-item class TilePlacedObjPartial above
// models -- separately named because this SAVE-side view's own car-slot POINTER ARRAY at +0x90
// numerically overlaps +0x94, a field TilePlacedObjPartial already models for a DIFFERENT real
// pointer type (a car object reached by dereferencing one of these array slots, not this
// struct's own +0x90 array) -- one C struct type can't declare both without an actual union, so
// this stays its own type, matching the project's established "multiple partial views of one
// real class" precedent (QueuedBigObjItemPartial vs TilePlacedObjPartial). Offsets confirmed
// directly from SaveBoardLayout's own raw disasm (Ghidra's decompile mislabeled this
// call's own "this" argument, forcing a raw objdump cross-check -- see that function's own
// header comment).
struct PlacedItemSaveViewPartial {
    unsigned char pad0x28[0x28];
    unsigned int dwArgAMaybe;    // +0x28, presumably set by this item's own InvokeArgAMaybe
                                  // (vtbl+0x1c, see TilePlacedObjPartial) -- read back directly
                                  // here, never through a virtual call
    unsigned char pad0x2c[0x40 - 0x2c];
    void *pKindDesc;         // +0x40, same field as TilePlacedObjPartial's own
    unsigned char pad0x44[0x7c - 0x44];
    char szCategoryName[12];    // +0x7c, same field as TilePlacedObjPartial's own
    Pair16 pos;          // +0x88, this item's final (offset-adjusted) placed x/y
    unsigned char pad0x8c[0x90 - 0x8c];
    TilePlacedObjPartial *carSlots[5]; // +0x90, 5 car-slot pointers (really CarNetObj*)
    unsigned char pad0xa4[0xbc - 0xa4];
    unsigned int dwPlacementArgB;     // +0xbc, same field as TilePlacedObjPartial's own
    unsigned char Unk0xc0Maybe;    // +0xc0, same field as TilePlacedObjPartial's own ("ready" flag)
};

// A runtime string buffer (uninitialized in the on-disk image -- .data/.bss, not a string
// literal; distinct from the ".sav"/"~curr" literals elsewhere in this file), copied into the
// saved layout's own szReloadDestScratch header field by SaveBoardLayout. Likely a
// savegame display-name/title cache -- not independently confirmed, kept opaque.
extern char DAT_004aa9fd[];

// Per-TU minimal placeholder for BigObj's own m_type0x63a category check -- src/phase2_probe.cpp
// already has its own disconnected `BigObj` placeholder (see that file's header comment); this
// one is intentionally separately-named (not a duplicate class-E finding) since it only needs
// ONE of BigObj's many leaf predicates and the two placeholders model different byte ranges.
struct BigObjTypeSetProbePartial {
    char pad0x63a[0x63a];
    unsigned char m_type0x63a;
    unsigned char IsType0x63aInSet(); // 0x44bd30, extern
};

// PeerTrainNodePartial (partial view of PeerTrainNode) is defined in the shared header, included
// at the top of this file. See src/PeerTrainNode.h.

// The PeerTrainSlotQueueMaybe singleton (DAT_004a98b0) and its methods (incl.
// SpawnOrAssignRandomTrain 0x44dc10 and ResetAllFields 0x44d870, previously a local
// PeerTrainSlotQueuePartial here) are modeled once in src/PeerTrainSlotQueueMaybe.h /
// src/PeerTrainSlotQueueMaybe.cpp (consolidated v323 per the never-duplicate-structs rule).

// The WidgetPickerObj0x477cc8 singleton embedded as BuildToolButton's own regionBMaybe
// (base 0x4aa5b8 + 0x260 = 0x4aa818) -- LoadLayoutAndPopulateBoard reaches it via this same literal address
// directly (confirmed: raw disasm loads the immediate 0x4aa818, not base+offset arithmetic),
// exactly like WidgetPicker.cpp's own HandleSavegameMenuNode reaches the identical object
// via its own `this`.
extern WidgetPickerObj0x477cc8 DAT_004aa818;

// The 4-member "edge placement" quartet: each computes where a train hand-off connector
// tile lands on one of the board's 4 screen edges, dispatched by DPlaySessionMgr::
// HandleQueuedTrainPlacement (0x43e370) by heading value (0/0x5a/0xb4/0x10e). Genuine
// __thiscall MEMBERS returning Pair16 by value -- Ghidra's "NetSessionEventQueue::"
// attribution is correct, not address-boxing (CORRECTED v352; the v3 reading of the raw
// disasm as "a stack-passed out-param cleaned up by `ret 4`, ECX only a scratch push/pop"
// mistook the hidden STRUCT-RETURN buffer pointer for an out-param, and the 4-byte
// `push ecx` stack-alloc idiom for a save of an unused `this`. The bodies do genuinely
// ignore `this`, which is what made the free-function reading survive so long.)
// Named geometrically (by the edge each one anchors to), not by compass heading -- the mapping is
// confirmed from that dispatcher's own decompile, but the heading VALUES themselves
// (0/0x5a/0xb4/0x10e, matching PlaceEdgeLinksAndFlush's own N/E/S/W labels) don't line
// up with true compass directions against this geometry (e.g. heading 0 maps to the BOTTOM
// edge here, not north) -- possibly a rotated coordinate frame, not independently confirmed,
// so kept purely geometric to avoid asserting the wrong mapping.

// All four EXACT since v352. They were parked from v3 as "pure instruction scheduling"
// (the `out` pointer loaded early/late relative to the original) on the strength of a
// `void __stdcall Compute...(Pair16 *out)` model. That model was wrong in TWO independent
// ways, and neither residual was schedulable away:
//   1. `g_worldBoard.wCols`/`wRows` were declared `unsigned short`, so `>> 1` compiled to
//      `shr`; the original emits `sar`. The fields are SIGNED `short` (fixed in
//      src/WorldBoardMaybe.h). A shift-instruction mismatch is a TYPE fact, never a
//      scheduling tie -- worth ~10000 asmscore points across the quartet.
//   2. These are `__thiscall` MEMBERS returning `Pair16` BY VALUE, not free `__stdcall`
//      functions with an out-param. The tell is the ABI signature in the epilogue: the
//      original leaves the hidden return-buffer pointer in EAX at `ret 4`, which is
//      exactly MSVC's hidden-struct-return convention (VC5 does NOT return this 4-byte
//      POD in EAX here). That convention is what pins the buffer load to EAX and forces
//      it LATE, right before the copy -- the entire "scheduling" residual.
// src/DPlaySessionMgr.cpp's caller-side `NetSessionEventQueueEdge` view had modeled the
// by-value return correctly since v3; only the callee side disagreed. See CODEGEN.md.

// FUNCTION: LOCO 0x41d920
Pair16 NetSessionEventQueue::ComputeLeftEdgePlacement() {
    Pair16 tmp;
    tmp.lo = 0;
    tmp.hi = (short)((g_worldBoard.wRows >> 1) - 1);
    return tmp;
}

// FUNCTION: LOCO 0x41d980
Pair16 NetSessionEventQueue::ComputeTopEdgePlacement() {
    Pair16 tmp;
    tmp.hi = 0;
    tmp.lo = (short)((g_worldBoard.wCols >> 1) - 1);
    return tmp;
}

// FUNCTION: LOCO 0x41d8f0
Pair16 NetSessionEventQueue::ComputeRightEdgePlacement() {
    Pair16 tmp;
    tmp.lo = (short)(g_worldBoard.wCols - 3);
    tmp.hi = (short)((g_worldBoard.wRows >> 1) - 1);
    return tmp;
}

// FUNCTION: LOCO 0x41d950
Pair16 NetSessionEventQueue::ComputeBottomEdgePlacement() {
    Pair16 tmp;
    tmp.lo = (short)((g_worldBoard.wCols >> 1) - 1);
    tmp.hi = (short)(g_worldBoard.wRows - 2);
    return tmp;
}

// FUNCTION: LOCO 0x41d320
// Places the 4 track/global-{e,w,n,s} edge-of-board connector tiles (item kinds
// 0xc42/0xc44/0xc46/0xc48, TrackGlobalLinkItemKindMaybe) at the 4 screen edges, one per compass
// heading (0/0x5a/0xb4/0x10e = N/E/S/W), each gated by DPlaySessionMgr::
// HasProviderSlotRoomInHeading -- i.e. a tile only gets placed on an edge where a
// connected multiplayer peer session has room in that heading. Also loads the caller-requested
// savegame name (caching it globally unless it's the "~curr" keep-current sentinel), then
// builds and loads a SECOND, independent savegame path derived from the currently-loaded
// backdrop bitmap's own path (its ".bmp" extension swapped for ".sav"). When DPlaySessionMgr::
// connectionMode == 2, also opportunistically flushes ready category-3 BigObj-family queue
// entries before placing the edge tiles. See docs/subsystems.md's NetSessionEventQueue
// entry (v126 paragraphs) for the full field-identification writeup this transcription is
// based on.
// PARKED (v127/v128), DIFF 368/616 (orig 671B, this compile 616B): a direct instruction-by-
// instruction disasm comparison (not just the byte-diff score) confirms every field offset,
// struct layout, parameter VALUE, and control-flow branch here is semantically correct --
// the prologue/string-building prefix through roughly relative offset 0x50 is a near-exact
// structural match (see the frame-size note below), and every one of the 4
// WorldBoardMaybe_PlaceObjectMaybe call sites pushes the identical (itemKind, x, y, flag, arg5)
// values as the original, just in a different push/spill ORDER. The residual is concentrated
// in register allocation (an extra `mov bl,al` register copy the original does that this
// compile elides) and per-heading-block short-value stack-slot placement (the original homes
// each block's computed x/y temps at slightly different [esp+N] offsets, likely driven by
// live-range overlap with earlier locals this compile doesn't reproduce) -- both classes
// already documented elsewhere in this file/CLAUDE.md as compiler-internal, not reliably
// source-steerable. One concrete unexplained gap: the overall frame is 4 bytes smaller here
// (0x108 vs the original's 0x10c) despite an exhaustive semantic match. v128 exhaustively
// triaged this: inlined x/y expressions, per-block-distinct locals, hoisted declaration order,
// AND a minimal-TU probe isolating just this function from its ctor/dtor/quartet siblings --
// all 4 produced BYTE-IDENTICAL compiled output to the baseline. CLOSED as intrinsic
// register/stack-coloring behavior, see docs/PARKED.md's own entry for the full triage list --
// no further probing planned absent a new concrete hypothesis.
char NetSessionEventQueue::PlaceEdgeLinksAndFlush(unsigned char *pszName) {
    char bLoadedOk = LoadLayoutAndPopulateBoard(pszName, 1, 1);
    if (bLoadedOk && _stricmp((char *)pszName, "~curr") != 0) {
        strcpy(DAT_004aa8f8, (char *)pszName);
    }

    unsigned char szBackdropSavPath[260];
    strcpy((char *)szBackdropSavPath, g_pBackdropDesc->szBmpPath + strlen(g_pInstallPathPrefix));
    strcpy((char *)szBackdropSavPath + strlen((char *)szBackdropSavPath) - 4, ".sav");
    LoadLayoutAndPopulateBoard(szBackdropSavPath, 0, 0);

    unsigned char bSavedFlagMaybe = DAT_004fd3dc;
    if (g_pDPlaySessionMgr->connectionMode == 2) {
        int nCount = pEvents.Count();
        if (nCount != 0) {
            int i2 = 0;
            do {
                QueuedBigObjItemPartial *pItem = (QueuedBigObjItemPartial *)pEvents.GetAt(i2);
                unsigned char cCategory = 0;
                if (pItem->pKindDesc != 0) {
                    cCategory = ((BigObjCategoryPartial *)pItem->pKindDesc)->categoryByte;
                }
                if ((cCategory == 3) && (pItem->dwTrackState == 3) &&
                    (pItem->pOwningTrain == (void *)1)) {
                    g_worldBoard.FlushQueuedBigObjMaybe((TilePlacedObj *)pItem, 1);
                }
                i2++;
                nCount = pEvents.Count();
            } while (i2 < nCount);
        }

        bSavedFlagMaybe = DAT_004fd3dc;
        DAT_004fd3dc = 1;
        short sX;
        short sY;
        TilePlacedObjPartial *pPlaced;

        if (g_pDPlaySessionMgr->IsType0()) {
            sX = (g_worldBoard.wCols >> 1) - 1;
            pPlaced = g_worldBoard.PlaceObject(0xc46, sX, 0, 0, 1);
            if (pPlaced != 0) {
                pPlaced->Unk0xc0Maybe = 0;
            }
        }
        if (g_pDPlaySessionMgr->IsType0xb4()) {
            sX = (g_worldBoard.wCols >> 1) - 1;
            sY = g_worldBoard.wRows - 2;
            pPlaced = g_worldBoard.PlaceObject(0xc48, sX, sY, 0, 1);
            if (pPlaced != 0) {
                pPlaced->Unk0xc0Maybe = 0;
            }
        }
        if (g_pDPlaySessionMgr->IsType0x5a()) {
            sX = g_worldBoard.wCols - 3;
            sY = (g_worldBoard.wRows >> 1) - 1;
            pPlaced = g_worldBoard.PlaceObject(0xc42, sX, sY, 0, 1);
            if (pPlaced != 0) {
                pPlaced->Unk0xc0Maybe = 0;
            }
        }
        if (g_pDPlaySessionMgr->IsType0x10e()) {
            sY = (g_worldBoard.wRows >> 1) - 1;
            pPlaced = g_worldBoard.PlaceObject(0xc44, 0, sY, 0, 1);
            if (pPlaced != 0) {
                pPlaced->Unk0xc0Maybe = 0;
            }
        }
    }
    DAT_004fd3dc = bSavedFlagMaybe;
    return bLoadedOk;
}

extern unsigned int __cdecl TileKind_GetCategory(unsigned int kindId);

// FUNCTION: LOCO 0x41d5c0
// The Load half of the savegame-commit path's Load/Save pair (sibling: SaveBoardLayout, still
// deferred). Loads a ThumbnailBmp-format layout from "<installPath><pszPath>", then places
// every one of its recorded objects onto the live WorldBoardMaybe (centered against the
// current board's own column/row count) and spawns every one of its recorded trains via
// PeerTrainSlotQueueMaybe. Called twice by PlaceEdgeLinksAndFlush above: once for the
// caller-requested savegame name (bResetTiles=1, bSkipDefaultFlag=1), once for a second,
// independent path derived from the current backdrop bitmap's own name with its extension
// swapped to ".sav" (bResetTiles=0, bSkipDefaultFlag=0). See docs/subsystems.md's
// NetSessionEventQueue entry for the full record-layout writeup this transcription is
// based on (ObjectPlacementRecord/CarSlotRecord offsets confirmed directly from
// Ghidra's own typed ushort*/int* pointer arithmetic in the decompile, not guesswork).
// PARKED (v129), DIFF 497/816: every one of the 37 external calls the original makes (the
// path-build strcpy/strcat pair, ThumbnailBmp_Load/IsLoadedMaybe/CloseStreamsMaybe,
// ResetAllTilesMaybe, the "~curr" _stricmp check + ReloadActiveSaveState backdrop-reload, the
// object-placement loop's PlaceObject/vtbl+0x1c/0x34/0x3c triple + the "PARTY" car-slot
// sub-loop, the train-spawn loop's PickRandomBigObjByCategory/SpawnOrAssignRandomTrain/
// SetCarsReady/vtbl+0x34) is confirmed present at the correct relative position via a
// direct disasm cross-check (asmscore.py --dump), not just inferred from compiling cleanly.
// The residual is concentrated in register allocation: the original keeps 4 callee-saved
// registers live (ebx/ebp/esi/edi) — ebp is REUSED partway through the function for two
// unrelated purposes (first as a cached copy of the pszPath argument for the early "~curr"
// check, then repurposed as the car-slot sub-array's own induction pointer) — while this
// compile only needs 3 (ebx/esi/edi), plus EH-scaffolding-state-transition position drift
// consistent with the already-documented "small local with a real ctor/dtor shifts stack
// traffic" class (CLAUDE.md). Tried one concrete lever: rewriting the car-slot sub-loop as a
// raw pointer walk (`CarSlotRecord *pSlot = arr; do {...; pSlot++;} while(...)`) to try to
// force the same induction-pointer register reuse the original shows — scored WORSE (630/825,
// reverted) rather than better, confirming the original's specific register-reuse choice isn't
// reachable by this source-level lever. No further probing planned within this session's
// budget; a fresh idea (not yet tried: reordering the object-count/train-count loops' local
// declarations, or hoisting pszPath into an explicit local before its first use) would be the
// next thing to try in a future session.
unsigned char NetSessionEventQueue::LoadLayoutAndPopulateBoard(unsigned char *pszPath, char bResetTiles,
                                                              char bSkipDefaultFlag) {
    ThumbnailBmp thumb;

    char szFullPath[264];
    strcpy(szFullPath, g_pInstallPathPrefix);
    strcat(szFullPath, (char *)pszPath);
    thumb.ThumbnailBmp_Load(szFullPath);

    if (!thumb.ThumbnailBmp_IsLoaded()) {
        thumb.ThumbnailBmp_CloseStreams();
        return 0;
    }

    // ThumbnailBmp::wWidth/wHeight are declared signed short (to match DPlaySessionMgr::
    // LayoutSet_LoadSlotBitmap's already-EXACT read of the same fields), but THIS call site's
    // raw disasm zero-extends them (`mov ecx,[..]; and ecx,0xffff`) -- same lever as
    // WidgetPickerObj0x477cc8::ReloadBackdropPreview's own identical cast.
    short sOffsetX = (g_worldBoard.wCols - (unsigned short)thumb.wWidth) / 2;
    short sOffsetY = (g_worldBoard.wRows - (unsigned short)thumb.wHeight) / 2;
    if (bResetTiles != 0) {
        g_worldBoard.ResetAllTiles();
    }
    if (_stricmp((char *)pszPath, "~curr") != 0) {
        DAT_004aa818.ReloadActiveSaveState((char *)thumb.szReloadDestScratch);
    }

    unsigned char bSavedFlagMaybe = DAT_004fd3dc;
    DAT_004fd3dc = 1;

    int nPlaced = 0;
    if (0 < thumb.nObjectCount) {
        do {
            ObjectPlacementRecord *pRec = thumb.GetNextObjectRecord();
            TilePlacedObjPartial *pPlaced = 0;
            if (pRec != 0) {
                pPlaced = g_worldBoard.PlaceObject(
                    pRec->wKindId, (short)(pRec->offset.lo + sOffsetX),
                    (short)(pRec->offset.hi + sOffsetY), 1, 1);
            }
            if (pPlaced != 0) {
                if (bSkipDefaultFlag == 0) {
                    pPlaced->Unk0xc0Maybe = 0;
                }
                pPlaced->ApplyRecordBlobMaybe(pRec->szCategoryNameBlob);
                if (pRec->wKindId != 0x852 &&
                    (TileKind_GetCategory(pRec->wKindId) != 3 ||
                     !((BigObjTypeSetProbePartial *)pPlaced->pKindDesc)->IsType0x63aInSet())) {
                    pPlaced->InvokeArgAMaybe(pRec->dwArgAMaybe);
                }
                pPlaced->dwPlacementArgB = pRec->dwArgBMaybe;

                for (int i = 0; i < 5; i++) {
                    CarSlotRecord *pSlot = &pRec->arrCarSlots[i];
                    if (pSlot->wCarKindId != 0) {
                        TilePlacedObjPartial *pCar = (TilePlacedObjPartial *)pPlaced->GetOrAllocCarSlot(pSlot->wCarKindId);
                        if (pCar != 0) {
                            if (_stricmp((char *)pSlot->szData, "PARTY") != 0) {
                                pCar->ApplyRecordBlobMaybe(pSlot->szData);
                            }
                            pCar->dwUnk0x94Maybe = pSlot->dwUnkMaybe;
                        }
                    }
                }
            }
            nPlaced++;
        } while (nPlaced < thumb.nObjectCount);
    }

    int nTrainIdx = 0;
    if (thumb.wTrainCount != 0) {
        do {
            TrainPlacementRecord *pTrainRec = thumb.GetNextTrainRecord();
            if (pTrainRec != 0) {
                void *pBigObj = g_NetSessionEventQueue.PickRandomBigObjByCategory(3);
                if (pBigObj != 0) {
                    PeerTrainNodePartial *pTrain = (PeerTrainNodePartial *)g_PeerTrainSlotQueue.SpawnOrAssignRandomTrain(pBigObj, pTrainRec);
                    if (pTrain != 0) {
                        pTrain->SetCarsReady(0);
                        pTrain->carSlots[0]->ApplyRecordBlobMaybe(pTrainRec->szCategoryNameBlob);
                    }
                }
            }
            nTrainIdx++;
        } while (nTrainIdx < thumb.wTrainCount);
    }

    thumb.ThumbnailBmp_CloseStreams();
    g_worldBoard.bBoardDirtyNeedsRebuildFlag = 1;
    DAT_004fd3dc = bSavedFlagMaybe;
    return 1;
}

// FUNCTION: LOCO 0x41d9b0
// The Save half of the savegame-commit path's Load/Save pair (sibling:
// LoadLayoutAndPopulateBoard above). Builds a ThumbnailBmp-format layout header (board
// dimensions + object/train counts, the exact mirror of LoadLayoutAndPopulateBoard's own
// header read) at "<installPath><pszPath>", then streams every placed object on pEvents
// (gated on its own Unk0xc0Maybe "ready" flag) and every PeerTrainSlotQueueMaybe train slot out
// via ThumbnailBmp's own record-writer pair (WriteObjectRecord/WriteTrainRecord,
// ex-FUN_00447f50/FUN_00447f80 -- confirmed genuine __thiscall ThumbnailBmp methods from their
// own decompile, each reading this+0x1cc, the same stream-pointer field
// ThumbnailBmp_CloseStreams/GetNextObjectRecord already establish). See
// docs/subsystems.md's NetSessionEventQueue entry for the full record-layout writeup.
// A raw objdump cross-check was required specifically for the WriteObjectRecord call
// site: Ghidra's own decompile mislabels its "this" argument as a wrong 4-byte stack local
// (auStack_2f0) instead of the real thumb object, unlike the sibling WriteTrainRecord call
// (correctly decompiled as this=thumb) -- the raw disasm (`lea ecx,[esp+0xcc]` right before
// the call at 0x41dbe8) confirms both calls really pass this=thumb.
// PARKED (v130), DIFF 372/865 (orig 909B): every field offset/struct layout/call shape here is
// confirmed via a direct disasm cross-check (asmscore.py --dump), same standard as the sibling
// LoadLayoutAndPopulateBoard. One concrete lever DID help: the placed item's own +0x88
// offset-x/y pair was originally modeled as two independent `short` fields, which compiled to
// two separate word stores where the original does one dword `mov` -- merging them into a
// single `Pair16 offset` field (assigned as one struct copy) closed that gap and
// dropped the residual from 444 to 372. Remaining residual is concentrated in: (1) register
// allocation/EH-scaffolding-position drift matching the same class already documented on
// LoadLayoutAndPopulateBoard and PlaceEdgeLinksAndFlush; (2) the car-slot sub-loop's
// wCarKindId write -- the original zero-extends the resourceId word into a full register
// then stores a WIDE dword (incidentally zeroing CarSlotRecord's own 2-byte pad as a
// side effect of the wider store), while this compile does a plain 16-bit field store (the pad
// is already zeroed up front by this function's own `memset(&rec,0,sizeof(rec))` instead) --
// semantically identical, but not reproducible as a narrower per-field store without writing
// unidiomatic direct pad-byte writes. No further probing planned within this session's budget.
unsigned char NetSessionEventQueue::SaveBoardLayout(unsigned char *pszPath) {
    ThumbnailBmp thumb;

    char szFullPath[264];
    strcpy(szFullPath, g_pInstallPathPrefix);
    strcat(szFullPath, (char *)pszPath);

    // Zeroes exactly the [wFormatTag, pPixels) header span (0x114 bytes) -- confirmed via the
    // original's own raw disasm (a 0x45-dword zeroing loop starting at wFormatTag); NOT
    // sizeof(ThumbnailBmp)-offsetof(...), which would also zero the trailing stream-pointer
    // fields past the on-disk header.
    memset(&thumb.wFormatTag, 0,
           offsetof(ThumbnailBmp, pPixels) - offsetof(ThumbnailBmp, wFormatTag));
    thumb.wFormatTag = 8;
    thumb.wWidth = g_worldBoard.wCols;
    thumb.wHeight = g_worldBoard.wRows;
    thumb.nObjectCount = nPlacedObjectCount;
    thumb.wTrainCount = g_PeerTrainSlotQueue.nActiveCount;
    strcpy((char *)thumb.szReloadDestScratch, DAT_004aa9fd);

    if (!thumb.ThumbnailBmp_Save(szFullPath)) {
        return 0;
    }

    int nCount = pEvents.Count();
    if (nCount != 0) {
        int i2 = 0;
        do {
            PlacedItemSaveViewPartial *pItem = (PlacedItemSaveViewPartial *)pEvents.GetAt(i2);
            if (pItem != 0 && pItem->Unk0xc0Maybe == 1) {
                ObjectPlacementRecord rec;
                memset(&rec, 0, sizeof(rec));
                rec.wKindId = (unsigned short)((BigObjResourceIdPartial *)pItem->pKindDesc)->resourceId;
                rec.offset = pItem->pos;
                rec.dwArgAMaybe = pItem->dwArgAMaybe;
                rec.dwArgBMaybe = pItem->dwPlacementArgB;
                strcpy((char *)rec.szCategoryNameBlob, pItem->szCategoryName);

                for (int j = 0; j < 5; j++) {
                    TilePlacedObjPartial *pCar = pItem->carSlots[j];
                    if (pCar != 0) {
                        rec.arrCarSlots[j].wCarKindId =
                            (unsigned short)((BigObjResourceIdPartial *)pCar->pKindDesc)->resourceId;
                        rec.arrCarSlots[j].dwUnkMaybe = pCar->dwUnk0x94Maybe;
                        strcpy(rec.arrCarSlots[j].szData, pCar->szCategoryName);
                    }
                }

                thumb.WriteObjectRecord(&rec);
            }
            i2++;
            nCount = pEvents.Count();
        } while (i2 < nCount);
    }

    for (int i3 = 0; i3 < 4; i3++) {
        PeerTrainNodePartial *pTrain = g_PeerTrainSlotQueue.aSlots[i3];
        if (pTrain != 0) {
            TrainPlacementRecord trainRec;
            memset(&trainRec, 0, sizeof(trainRec));
            for (int j = 0; j < 4; j++) {
                TilePlacedObjPartial *pCar = pTrain->carSlots[j];
                if (pCar != 0) {
                    trainRec.dwCarKindIds[j] = ((BigObjResourceIdPartial *)pCar->pKindDesc)->resourceId;
                    trainRec.dwCarCategories[j] = pCar->nCarCategory;
                }
            }
            strcpy((char *)trainRec.szCategoryNameBlob, pTrain->carSlots[0]->szCategoryName);
            thumb.WriteTrainRecord(&trainRec);
        }
    }

    thumb.ThumbnailBmp_CloseStreams();
    if (_stricmp((char *)pszPath, "~curr") != 0) {
        strcpy(DAT_004aa8f8, (char *)pszPath);
    }
    return 1;
}

// FUNCTION: LOCO 0x41dd40
// Tick every registered world object's animation one frame: walk the whole pEvents registry and
// dispatch slot 10 (AdvanceAnimFrameMaybe) on each live entry. NULL slots are skipped rather
// than compacted -- the registry is sparse by design (BigObj_Remove leaves holes).
//
// Count() is re-read every iteration rather than hoisted, and that is the original's own shape,
// not a transcription artifact: the guard at the top is `test eax,eax / jbe` and the bottom of
// the loop calls slot 0x2c again before `cmp edi,eax / jb`. Both comparisons are UNSIGNED, so
// the induction variable is `unsigned int` -- the same reason the sibling loop at 0x41d9b0
// carries an unsigned `i`.
void NetSessionEventQueue::AdvanceAllAnimFramesMaybe()
{
    for (unsigned int i = 0; i < pEvents.Count(); i++) {
        AnimDescRefObj0x477488 *pObj = (AnimDescRefObj0x477488 *)pEvents.GetAt(i);
        if (pObj != 0) {
            pObj->AdvanceAnimFrameMaybe();
        }
    }
}

// FUNCTION: LOCO 0x41dd80 (?BigObj_CreateAndInsert@NetSessionEventQueue@@)
// Registry create/insert for the world-object class family (BigObj-family:
// TrackDepotTileObj/TrackConnectorTileObj/TrackTileObj/TilePlacedObj,
// dispatched by TileKind category + BigObj::m_type0x63a via the already-byte-matched
// IsType0x63aInSet/IsType0x63aInSet1234 predicates, src/phase2_probe.cpp). `this` is the
// NetSessionEventQueue singleton (&DAT_004a9990), NOT a BigObj instance -- see
// docs/subsystems.md's BigObj entry for the full mistyping-correction writeup: the vtable calls
// on (this->pEvents) are really Add (vtbl+0x34), and this->nPlacedObjectCount is the live queued
// count, incremented here (paired decrement in the sibling BigObj_Remove). Sole caller:
// WorldBoardMaybe::WorldBoardMaybe_PlaceObjectMaybe (0x4550c0, not yet transcribed).
// EFFECTIVE MATCH, DIFF 4/368 (204/204... 117/117 insns matching, byte_diff=4). Uses real
// `new ClassName(kindId)` expressions (src/TilePlacedObj.h/.cpp model the full 4-leaf-type
// base-class ctor chain) rather than the old manual `::operator new` + explicit
// InitFieldsMaybe() call this function used before v207 -- DIFF dropped 192->30 from that
// alone, then ->4 once `this[1].vtbl`-shaped access (the "adjacent global" byte at +0x18)
// was recognized as a genuine NetSessionEventQueue member (dwReadyBigObjCount,
// see the class def above) rather than a separately-named global -- a plain global-by-name
// reference compiles to absolute addressing regardless of memory adjacency, so the
// original's ebp-relative [ebp+0x18] access proves it's a real `this->field`. Residual: the
// 4 leaf `new` expressions' /GX alloc-protection EH state numbers (the compiler's internal
// 0/1/2/3 tags, one per protected `new`) come out cyclically shifted by one position vs the
// original (mine: TilePlacedObj=0,TypeSet=1,TypeSet1234=2,TrackTileObj=3; orig:
// TilePlacedObj=3,TypeSet=0,TypeSet1234=1,TrackTileObj=2) -- tried flipping the outer
// if/else polarity to reorder lexical `new` encounter order (matching the state numbers'
// apparent order), which INSTEAD wrecked the whole function (264/372) by also flipping which
// branch is the fall-through block (TilePlacedObj must stay the `else`/fall-through arm
// per the original's own block layout).
//
// v360 re-ran that polarity flip under the SP3 toolchain (pickup item 3's "re-score pre-v358
// autopsies" sweep) and it still lands on exactly DIFF 264/372 -- so this residual is NOT an
// RTM artifact. The mechanism is now understood and the two requirements are genuinely in
// conflict: /GX EH state tags ARE numbered in lexical `new` order (the original's 0,1,2,3 run
// TrackDepot -> TrackConnector -> TrackTile -> TilePlacedObj, i.e. the `==3` chain written
// FIRST), but VC5 does not invert an if/else -- it always emits the `then` arm as the
// fall-through -- and the original's fall-through arm is the TilePlacedObj one. Getting the
// state numbers right therefore costs the block layout, at 4 bytes vs. 260. Any future fix
// needs a source shape that puts the chain lexically first while still leaving TilePlacedObj
// as the fall-through block; plain if/else polarity cannot express that. Do not re-grind on
// the polarity axis.
TilePlacedObjPartial *NetSessionEventQueue::BigObj_CreateAndInsert(unsigned int kindId) {
    TilePlacedObjPartial *pObj;

    if ((unsigned char)TileKind_GetCategory(kindId) != 3) {
        pObj = (TilePlacedObjPartial *)new TilePlacedObj(kindId);
    } else {
        BigObj *pDesc = (BigObj *)g_UIResources.TileKind_GetOrLoadDescriptor(kindId);
        if (pDesc->IsType0x63aInSet()) {
            pObj = (TilePlacedObjPartial *)new TrackDepotTileObj(kindId);
        } else if (pDesc->IsType0x63aInSet1234()) {
            pObj = (TilePlacedObjPartial *)new TrackConnectorTileObj(kindId);
        } else {
            pObj = (TilePlacedObjPartial *)new TrackTileObj(kindId);
        }
    }

    if (pObj == 0) {
        return 0;
    }
    if (pObj->bValid != 1) {
        pObj->ScalarDelete(1);
        return 0;
    }

    pEvents.Add(pObj);
    if (((BigObj *)pObj->pKindDesc)->bCountedInReadyBigObjCount != 0) {
        dwReadyBigObjCount = dwReadyBigObjCount + 1;
    }
    nPlacedObjectCount = nPlacedObjectCount + 1;
    return pObj;
}

// FUNCTION: LOCO 0x41def0 (?BigObj_Remove@NetSessionEventQueue@@)
// Registry remove/destroy counterpart to BigObj_CreateAndInsert above (same `this`
// mistyping correction applies -- see docs/subsystems.md's BigObj entry). Unqueues pItem from
// pEvents if present (RemoveAt, decrementing nPlacedObjectCount/dwReadyBigObjCount to
// match the create side), then a special case: if pItem is itself a "global track-link"-shaped
// tile (category 0xc, resourceId > 0x3010 and odd) OR a "points/switch, orientation {0x12,0x13}"
// tile (category 3, IsType0x63aInSet12), scans its 4 board-adjacent neighbors for the FIRST one
// that itself satisfies the OTHER of those two shapes and, if found, zeroes 4 of that neighbor's
// own fields and flushes its queued BigObj via WorldBoardMaybe::FlushQueuedBigObjMaybe (which
// itself tail-calls back into this same function) -- a paired-tile hand-off, matching how
// PlaceEdgeLinksAndFlush's own "global track-link" tiles pair with a neighboring points tile
// (m_type0x63a docs' state enum). Finally, optionally spawns a despawn "puff of smoke" effect
// at the tile's own center (both branches of the DAT_00485234 check compute the IDENTICAL
// position -- confirmed via raw disasm, not a decompiler artifact; only the trailing mobility
// flag argument differs -- transcribed faithfully as a genuine, if redundant, // sic source
// quirk) before releasing pItem via its own scalar-deleting-dtor slot.
// v207-208: DIFF dropped 368/498 -> 260/518 (true len 515) across 3 fixes: (1) the same
// dwReadyBigObjCount real-member fix as BigObj_CreateAndInsert (this[1].vtbl at
// +0x18 is genuinely this->dwReadyBigObjCount, not the separate g_-named global);
// (2) the pEvents search loop was `if (Count()!=0) { do {...} while(i<nCount); }` --
// the documented "do-while peeled when entry is gated by a distinct outer guard" family
// (CLAUDE.md) -- rewritten as a plain `while (i < pEvents.Count())` (i declared
// `unsigned int`, matching Count()'s real unsigned comparison form in the original disasm --
// expect the resulting signed/unsigned mismatch compiler warning, it's intentional); (3) the
// paired-tile hand-off's 4-field neighbor reset (Unk0xc4/c8/cc/d0Maybe, all zeroed together)
// needed `memset(&pNeighbor->Unk0xc4Maybe, 0, 4*sizeof(unsigned int))` instead of 4 separate
// `= 0;` statements -- the original computes ONE `lea` into the 4-field block and stores via
// offset-relative addressing from it; a bare pointer LOCAL cached to the same address had
// ZERO effect (tried and reverted), only memset's own codegen reproduced the shared-base
// shape. Also fixed a real (if byte-match-neutral) bug while duplicating the despawn-effect
// call per DAT_00485234 branch (needed to stop /O2 folding the identical-position arms away,
// see the "sic" note below): the literal mobility-flag argument had the branches backwards
// (now DAT_00485234!=1 -> flag 1, DAT_00485234==1 -> flag 0, matching the original's real
// fall-through/jump-taken split, confirmed via raw disasm). Content-complete, still NOT BYTE-
// MATCHED -- remaining residual (score ~56k, was ~278k) is 2 structurally-different loop-exit
// jump targets on the two neighbor-search do-while loops (both `dir<4`, cross-jump geometry,
// tried an explicit `goto tail;` on the 2nd loop to unify with the 1st's -- zero effect,
// reverted) plus one instruction-scheduling/register-swap tie-break in the effect-spawn
// branch pair -- own residual, not triaged further this session, see docs/PARKED.md.
// v209: `dir` widened from `int` to `unsigned int` in both loops -- the original's own back-
// edge test is unsigned (`jb`/raw disasm at 0x41dfcc/0x41e056), matching the same lever that
// fixed the pEvents loop above. Score UNCHANGED (56249 -> 56249): the deeper residual is
// the branch SHAPE, not signedness -- the original compiles each loop as short-backward-jb-
// continue + near-forward-unconditional-jmp-exit (the canonical do-while shape, entry reached
// by fallthrough in both binaries alike), while our candidate compiles the inverse: near-
// forward-conditional-jae-exit + short-backward-unconditional-jmp-continue (1 byte heavier per
// loop, 3 extra bytes total vs the original's true 515). Checked whether the shared tail
// (0x41e07d) is reached by a 3rd path beyond the 2 loop exits that might explain the merge --
// it's reached by 4 paths total (2 early-skip guards + 2 loop exits), all already correctly
// modeled via the single `tail:` label; no new lever found. Given 2 independent prior
// experiments already ruled out (for-loop conversion, explicit goto-unification on the 2nd
// loop), this is an intrinsic block-layout/trace-scheduling tie-break (Yoda lesson #15's
// family) -- don't re-grind without a genuinely new idea.
void NetSessionEventQueue::BigObj_Remove(TilePlacedObjPartial *pItem, unsigned int bSpawnEffect) {
    if (pItem == 0) {
        return;
    }

    unsigned int i = 0;
    while (i < pEvents.Count()) {
        void *pFound = pEvents.GetAt(i);
        if (pFound == pItem) {
            pEvents.RemoveAt(i);
            nPlacedObjectCount = nPlacedObjectCount - 1;
            if (((BigObj *)pItem->pKindDesc)->bCountedInReadyBigObjCount != 0) {
                dwReadyBigObjCount = dwReadyBigObjCount - 1;
            }
            break;
        }
        i++;
    }

    BigObj *pDesc = (BigObj *)pItem->pKindDesc;
    unsigned char category = (pDesc == 0) ? 0 : pDesc->categoryByte;
    TilePlacedObjPartial *pNeighbor = 0;

    if (category == 0xc) {
        int resourceId = (pDesc == 0) ? -1 : pDesc->resourceId;
        if (0x3010 < resourceId) {
            resourceId = (pDesc == 0) ? -1 : pDesc->resourceId;
            if (resourceId % 2 != 0) {
                pItem->bValid = 0;
                unsigned int dir = 0;
                do {
                    pNeighbor = g_worldBoard.GetNeighborObject(pItem, dir);
                    if (pNeighbor != 0 && pNeighbor->bValid == 1) {
                        BigObj *pNDesc = (BigObj *)pNeighbor->pKindDesc;
                        unsigned char nCat = (pNDesc == 0) ? 0 : pNDesc->categoryByte;
                        if (nCat == 3 && pNDesc->IsType0x63aInSet12()) {
                            goto flushNeighbor;
                        }
                    }
                    dir++;
                } while (dir < 4);
                goto tail;
            }
        }
    }

    category = (pDesc == 0) ? 0 : pDesc->categoryByte;
    if (category == 3 && pDesc->IsType0x63aInSet12()) {
        pItem->bValid = 0;
        unsigned int dir = 0;
        do {
            pNeighbor = g_worldBoard.GetNeighborObject(pItem, dir);
            if (pNeighbor != 0 && pNeighbor->bValid == 1) {
                BigObj *pNDesc = (BigObj *)pNeighbor->pKindDesc;
                unsigned char nCat = (pNDesc == 0) ? 0 : pNDesc->categoryByte;
                if (nCat == 0xc) {
                    int nResId = (pNDesc == 0) ? -1 : pNDesc->resourceId;
                    if (0x3010 < nResId) {
                        nResId = (pNDesc == 0) ? -1 : pNDesc->resourceId;
                        if (nResId % 2 != 0) {
                            goto flushNeighbor;
                        }
                    }
                }
            }
            dir++;
        } while (dir < 4);
    }

tail:
    if ((unsigned char)bSpawnEffect != 0) {
        BigObj *pd = (BigObj *)pItem->pKindDesc;
        int x, y;
        // sic: both arms of this check compute the IDENTICAL position (confirmed via raw
        // disasm) -- only the mobility-flag argument to EffectSpawner_SpawnAtPosition
        // actually depends on it. Duplicated per-arm call (not a shared/ternary flag value)
        // -- matches CLAUDE.md's documented "variadic-call-arg-picking branch" idiom: a
        // single shared call fed a computed flag gets its identical-arm branch folded away
        // by /O2, but the original keeps a real cmp/jne here, so the call itself must be
        // duplicated per arm with a literal 0/1 constant.
        if (DAT_00485234 != 1) {
            y = pItem->nPosY + (pd->nativeHeight >> 1);
            x = pItem->nPosX + (pd->nativeWidth >> 1);
            DAT_004fd220.EffectSpawner_SpawnAtPositionMaybe(0x3860, 1, 'W', x, y, 1);
        } else {
            y = pItem->nPosY + (pd->nativeHeight >> 1);
            x = pItem->nPosX + (pd->nativeWidth >> 1);
            DAT_004fd220.EffectSpawner_SpawnAtPositionMaybe(0x3860, 0, 'W', x, y, 1);
        }
    }
    pItem->ScalarDelete(1);
    return;

flushNeighbor:
    memset(&pNeighbor->Unk0xc4Maybe, 0, 4 * sizeof(unsigned int));
    g_worldBoard.FlushQueuedBigObjMaybe((TilePlacedObj *)pNeighbor, bSpawnEffect);
    goto tail;
}

// Picks one already-placed pEvents entry at random, out of those matching `category`. Five
// selectors share one shape: count the matches, draw an ordinal in [1, count], then walk the
// list again and keep the entry whose running match ordinal reaches it. Two of the five skip the
// counting pass because a running total is already maintained elsewhere -- case 2 uses the
// registry's own dwReadyBigObjCount (kept by BigObj_CreateAndInsert/BigObj_Remove off the very
// same bCountedInReadyBigObjCount flag the predicate tests), and the default arm uses the tile
// kind descriptor's own nLiveInstanceCountMaybe.
//
// `category` is a combined selector, not just a descriptor category:
//   -1        any placed object at all -- no predicate, index straight off nPlacedObjectCount
//   0 / 1 / 4 category-3 track objects in track state 3, filtered by OWNERSHIP: 0 = unowned,
//             1 = the ITEMKIND_TRACK_GLOBAL_* sentinel (TrackConnectorTileObj::pOwningTrain's
//             `(void *)1`), 4 = "any owner" (the filter is skipped outright)
//   2         objects whose kind descriptor is flagged bCountedInReadyBigObjCount
//   3         category-3 objects whose kind is one of the 4 depot orientations
//   other     treated as a literal tile kind id: resolve the descriptor and match on resourceId
//
// The ordinal draw is RandRange.h's macro, in exactly the two-armed swapped-argument form that
// header documents: the source branches on the sign itself and passes (1, count) or (count, 1).
// The macro's own `hi - lo + 1 == 0` guard folds away in the first arm because the count was
// already proven non-zero one branch earlier, which is why only the swapped arm keeps its test.
//
// EFFECTIVE MATCH (884 B vs 888, insns 348/350, total 192053). All FIVE arms are structurally
// correct -- the complete diff over 350 instructions is 61 rows, and every single one is a
// register-assignment consequence; there is no structural disagreement anywhere in the body.
// The whole residual is one callee-saved allocation choice: the original spends EBP on the
// per-arm nTarget/nSeen and therefore re-reads `category` from its incoming stack slot
// (`mov ecx,[esp+0x18]`) at the one site that needs it, while cl here parks `category` in EBP
// for the whole function and allocates nTarget/nSeen elsewhere. The 2-instruction shortfall is
// exactly that: the original's `mov ecx,[esp+0x18]` reload plus one of its two `xor edi,edi`
// loop-counter zeroings (cl reaches those with an already-zero register), against one extra
// instruction of mine in the case -1 arm, where the original folds &pEvents and the vtable load
// into `lea ecx,[esi+4]; mov eax,[ecx]` and cl emits a separate base and vtable register.
//
// ⚠ Ghidra's decompiler is BADLY WRONG on this function and must not be used as the model: it
// mis-reads the `push ecx` local-slot reservation, so the 4-byte result slot at [esp+0x10]
// never appears (every arm reads `return 0`, when the real epilogue is `mov eax,[esp+0x10]`)
// and the `category` parameter surfaces as a bogus `unaff_retaddr`. It also drops two blocks as
// unreachable. The frame was re-derived by hand from the raw disasm.
//
// One lever DID pay and is baked in: NetSessionEventQueue::nPlacedObjectCount is UNSIGNED, not
// `int`. The case -1 arm is the only site in the codebase that can tell the two models apart --
// `rand() % nPlacedObjectCount` emits an unsigned `xor edx,edx; div` in the original, where an
// `int` field promotes it to a signed `cdq; idiv`. The retype was measured repo-wide and is
// byte-neutral everywhere else (zero per-file changes), and it makes the field agree with its
// sibling dwReadyBigObjCount.
// Lever measured and REFUTED (do not re-run): hoisting the loop locals (i/nTarget/nSeen) out of
// the per-case blocks to function scope, VC5-old-for-scope style, is BYTE-IDENTICAL -- VC5's
// allocator is live-range based, not scope based (the same finding as v461's own scoping probe).
// See docs/PARKED.md.
// FUNCTION: LOCO 0x41e1f0
void *NetSessionEventQueue::PickRandomBigObjByCategory(int category) {
    void *pResult = 0;
    int nCount = 0;

    switch (category) {
    case -1:
        if (nPlacedObjectCount != 0) {
            pResult = pEvents.GetAt(rand() % nPlacedObjectCount);
        }
        break;

    case 0:
    case 1:
    case 4: {
        unsigned int i;
        for (i = 0; i < pEvents.Count(); i++) {
            QueuedBigObjItemPartial *pItem = (QueuedBigObjItemPartial *)pEvents.GetAt(i);
            BigObj *pDesc = (BigObj *)pItem->pKindDesc;
            unsigned char cat = (pDesc == 0) ? 0 : pDesc->categoryByte;
            if (cat == 3 && pItem->dwTrackState == 3 &&
                (category == 4 || pItem->pOwningTrain == (void *)category)) {
                nCount++;
            }
        }
        if (nCount != 0) {
            int nTarget;
            if (nCount >= 1) {
                nTarget = RAND_RANGE_MAYBE(1, nCount);
            } else {
                nTarget = RAND_RANGE_MAYBE(nCount, 1);
            }
            int nSeen = 0;
            for (i = 0; i < pEvents.Count(); i++) {
                if (nSeen == nTarget) {
                    break;
                }
                QueuedBigObjItemPartial *pItem = (QueuedBigObjItemPartial *)pEvents.GetAt(i);
                BigObj *pDesc = (BigObj *)pItem->pKindDesc;
                unsigned char cat = (pDesc == 0) ? 0 : pDesc->categoryByte;
                if (cat == 3 && pItem->dwTrackState == 3 &&
                    (category == 4 || pItem->pOwningTrain == (void *)category)) {
                    nSeen++;
                    pResult = pItem;
                }
            }
        }
        break;
    }

    case 3: {
        unsigned int i;
        for (i = 0; i < pEvents.Count(); i++) {
            QueuedBigObjItemPartial *pItem = (QueuedBigObjItemPartial *)pEvents.GetAt(i);
            BigObj *pDesc = (BigObj *)pItem->pKindDesc;
            unsigned char cat = (pDesc == 0) ? 0 : pDesc->categoryByte;
            if (cat == 3 && pDesc->IsType0x63aInSet()) {
                nCount++;
            }
        }
        if (nCount != 0) {
            int nTarget;
            if (nCount >= 1) {
                nTarget = RAND_RANGE_MAYBE(1, nCount);
            } else {
                nTarget = RAND_RANGE_MAYBE(nCount, 1);
            }
            int nSeen = 0;
            for (i = 0; i < pEvents.Count(); i++) {
                if (nSeen == nTarget) {
                    break;
                }
                QueuedBigObjItemPartial *pItem = (QueuedBigObjItemPartial *)pEvents.GetAt(i);
                BigObj *pDesc = (BigObj *)pItem->pKindDesc;
                unsigned char cat = (pDesc == 0) ? 0 : pDesc->categoryByte;
                if (cat == 3 && pDesc->IsType0x63aInSet()) {
                    nSeen++;
                    pResult = pItem;
                }
            }
        }
        break;
    }

    case 2:
        if (dwReadyBigObjCount != 0) {
            unsigned int nTarget;
            if (dwReadyBigObjCount >= 1) {
                nTarget = RAND_RANGE_MAYBE(1, dwReadyBigObjCount);
            } else {
                nTarget = RAND_RANGE_MAYBE(dwReadyBigObjCount, 1);
            }
            unsigned int nSeen = 0;
            unsigned int i;
            for (i = 0; i < pEvents.Count(); i++) {
                if (nSeen == nTarget) {
                    break;
                }
                QueuedBigObjItemPartial *pItem = (QueuedBigObjItemPartial *)pEvents.GetAt(i);
                // sic: no null guard on pKindDesc here, unlike every other arm.
                if (((BigObj *)pItem->pKindDesc)->bCountedInReadyBigObjCount != 0) {
                    nSeen++;
                    pResult = pItem;
                }
            }
        }
        break;

    default: {
        BigObj *pDesc = (BigObj *)g_UIResources.TileKind_GetOrLoadDescriptor(category);
        if (pDesc != 0 && pDesc->nLiveInstanceCountMaybe != 0) {
            int nTarget;
            if (pDesc->nLiveInstanceCountMaybe >= 1) {
                nTarget = RAND_RANGE_MAYBE(1, pDesc->nLiveInstanceCountMaybe);
            } else {
                nTarget = RAND_RANGE_MAYBE(pDesc->nLiveInstanceCountMaybe, 1);
            }
            int nSeen = 0;
            unsigned int i;
            for (i = 0; i < pEvents.Count(); i++) {
                if (nSeen == nTarget) {
                    break;
                }
                QueuedBigObjItemPartial *pItem = (QueuedBigObjItemPartial *)pEvents.GetAt(i);
                // sic: no null guard on pKindDesc here either.
                if (((BigObj *)pItem->pKindDesc)->resourceId == category) {
                    nSeen++;
                    pResult = pItem;
                }
            }
        }
        break;
    }
    }
    return pResult;
}

#include "PlacementCursorMaybe.h" // PlacementCursorMaybe_004854c8.ReleaseHoverObjMaybe --
                                  // mid-file include, the DPlaySessionMgr end-of-file pattern

// FUNCTION: LOCO 0x41e100
// Board-object reset, run as part of WorldBoardMaybe's ResetAllTilesMaybe (its sole code
// caller): drop the placement cursor's hover object, delete every registered placed object
// (pEvents' vtable slot 6, +0x18 = RemoveAndDeleteAll) and zero both live counters. The
// un-namespaced Ghidra body is vtable slot 1 of the class's own 0x4779d0 table (slot 0 =
// BigObj_Remove) -- carried here in the free __fastcall form (the AppWindow.cpp
// escape-hatch pattern): the sole call site passes the singleton explicitly either way,
// byte-identical to the member shape. TODO: idiom -- fold onto the class as its slot-1
// virtual once the 0x4779d0 table's ownership is modeled.
void __fastcall NetSessionEventQueue_ResetPlacedObjectsMaybe(NetSessionEventQueue *pQueue)
{
    PlacementCursorMaybe_004854c8.ReleaseHoverObjMaybe();
    pQueue->pEvents.RemoveAndDeleteAll();
    pQueue->nPlacedObjectCount = 0;
    pQueue->dwReadyBigObjCount = 0;
}

// Cross-TU EffectSpawner callees with no shared-header declaration yet (the FrameDriver.cpp
// pattern): the list-clear is 0x423d00 (src/EffectSpawner.cpp), the per-frame tick is
// 0x423d70 (FrameDriver.cpp already declares it under the same name).
void __fastcall EffectSpawner_ClearBothListsMaybe(EffectSpawner *pSpawner);   // 0x423d00, src/EffectSpawner.cpp

// FUNCTION: LOCO 0x41e120
// Board rebuild from the placed-object registry (declared on the class in
// NetSessionEventQueue.h; callers: TutorialWnd::OnExit's default arm and
// BuildToolButton::HandleMenuCommandMaybe): dirty-mark the board, play UI sound 0x5026,
// clear both effect-spawner lists and tear down every peer-train slot, then -- bracketed by
// a placement-cursor capture grab/release -- walk pEvents handing each entry to
// WorldBoardMaybe::FlushQueuedBigObjMaybe. A successful flush EVICTS the entry and
// decrements nPlacedObjectCount, so the index only advances on failure; every time the
// draining count crosses a multiple of 10 the loop runs one EffectSpawner tick plus a full
// UpdateDirtyTiles pass (progressive repaint during the rebuild).
void NetSessionEventQueue::RebuildBoardFromPlacedObjectsMaybe()
{
    g_worldBoard.bBoardDirtyNeedsRebuildFlag = 1;
    g_UIResources.PlayUiSound(0x5026);
    EffectSpawner_ClearBothListsMaybe(&DAT_004fd220);
    g_PeerTrainSlotQueue.TeardownAllSlotsMaybe();
    if (nPlacedObjectCount != 0) {
        PlacementCursorMaybe_004854c8.SetCursorCapture(1, 1, 1);
        int i = 0;
        while (i != (int)nPlacedObjectCount) {
            TilePlacedObj *pItem = (TilePlacedObj *)pEvents.GetAt(i);
            if (nPlacedObjectCount % 10 != 0) {
                if (g_worldBoard.FlushQueuedBigObjMaybe(pItem, 0) == 0) {
                    i++;
                }
            } else {
                if (g_worldBoard.FlushQueuedBigObjMaybe(pItem, 1) == 0) {
                    i++;
                }
                DAT_004fd220.EffectSpawner_TickMaybe();
                g_worldBoard.UpdateDirtyTiles(0);
            }
        }
        PlacementCursorMaybe_004854c8.SetCursorCapture(1, 1, 0);
    }
}

#ifdef LOCO_PORT
// ─── PORT SCAFFOLDING (no original counterpart) ────────────────────────────────
// XC 6 of 13: g_NetSessionEventQueue (DAT_004a9990), NetSessionEventQueue::NetSessionEventQueue
// (0x41d250).
//
// The original constructs this global from the CRT's C++ dynamic-initializer table (.CRT$XC),
// which the port's zero-filled .bss mirror has no equivalent of. Declared in
// port/PortGlobalCtors.h, called from link/init_globals.cpp -- see either for the full story.
#include <new.h>
#include "PortGlobalCtors.h"

void Port_Construct_g_NetSessionEventQueue(void) {
    new (&g_NetSessionEventQueue) NetSessionEventQueue();
}
#endif // LOCO_PORT
