// Obj0x4779e0 -- the BigObj-family base's own methods (TU cluster 0x41e600-0x41f2b0:
// dtor 0x41e600/0x41e620, Load 0x41e6e0, ParseTokenField 0x41e9f0, ParsePhysicalOccupancyMaybe
// 0x41efa0, entry_exit handler 0x41f0c0, seq-record parser 0x41f2b0 -- Load and the last two
// handlers untranscribed so far).
#include "CursorDesc.h"
#include "TimeOfDayMaybe.h"
#include "DSoundChannel.h" // RFIndex/g_RFIndex/g_pInstallPathPrefix/_free

#include <windows.h>
#include <fstream.h>
#include <strstrea.h>
#include <stdio.h>
#include <string.h>

extern unsigned int __cdecl TileKind_GetCategory(unsigned int kindId); // 0x446030

// FUNCTION: LOCO 0x41e620
// Obj0x4779e0::~Obj0x4779e0 (Ghidra: Obj0x4779e0::FUN_0041e620) -- frees the 3 owned
// keyword-record arrays (InsertSeq/MobileSeq/TotalVisits values), then the compiler's own
// teardown destroys the two TimeOfDayMaybe "shifts" embeds (+0x548 then +0x534, reverse
// declaration order) and the CursorDesc base.
Obj0x4779e0::~Obj0x4779e0() {
    if (paInsertSeqValues != NULL) {
        delete paInsertSeqValues;
        paInsertSeqValues = NULL;
    }
    if (paMobileSeqValues != NULL) {
        delete paMobileSeqValues;
        paMobileSeqValues = NULL;
    }
    if (paTotalVisitsValues != NULL) {
        delete paTotalVisitsValues;
        paTotalVisitsValues = NULL;
    }
}

// FUNCTION: LOCO 0x41e600 (??_GObj0x4779e0 scalar dtor)
// Auto-generated by the virtual dtor above -- this COMDAT has no source line of its own.

// FUNCTION: LOCO 0x41e9f0
// Obj0x4779e0::ParseTokenField -- this class's own vtable-slot-3 override (vtable 0x4779e0;
// Ghidra: Obj0x4779e0::ParseTokenField, synced). The extended keyword-dispatch pass: frees the
// 3 owned keyword-record arrays, then loops on "keyword value..." tokens until the "-9"
// record-end sentinel or a stream error: physical_occupancy -> ParsePhysicalOccupancyMaybe,
// bitmap_occupancy -> inline aBitmapOccupancySlotGrid fill, entry_exit -> ParseEntryExitMaybe,
// plus the assorted scalar/array employee/minifig/seq fields. On loop exit derives
// bFootprintHotspotEncodedMaybe from the footprint Y-step count and the bitmap-occupancy row
// count, and zeroes bSpawnVariance when no PossibleMinifigs entry survived parsing.
unsigned char Obj0x4779e0::ParseTokenField(istream *pStream) {
    unsigned short usValue;
    int nMinifigCount = 0;
    unsigned char bResult = 1;
    unsigned short usRows;
    unsigned short usCols;
    char szTok[264];

    if (paInsertSeqValues != NULL) {
        delete paInsertSeqValues;
        paInsertSeqValues = NULL;
    }
    if (paMobileSeqValues != NULL) {
        delete paMobileSeqValues;
        paMobileSeqValues = NULL;
    }
    if (paTotalVisitsValues != NULL) {
        delete paTotalVisitsValues;
        paTotalVisitsValues = NULL;
    }

    *pStream >> szTok;
    while (_stricmp(szTok, "-9") != 0 && !pStream->eof() && !pStream->fail()) {
        if (_stricmp(szTok, "physical_occupancy") == 0) {
            ParsePhysicalOccupancyMaybe(pStream);
        } else if (_stricmp(szTok, "bitmap_occupancy") == 0) {
            int nRow;
            int nCol;

            *pStream >> usCols >> usRows;
            bBitmapOccupancyCols = (unsigned char)usCols;
            bBitmapOccupancyRows = (unsigned char)usRows;
            nRow = 0;
            if (bBitmapOccupancyRows > 0) {
                do {
                    nCol = 0;
                    if (bBitmapOccupancyCols > 0) {
                        do {
                            *pStream >> usCols;
                            aBitmapOccupancySlotGrid[nCol][nRow] = (unsigned char)usCols;
                            nCol++;
                        } while (nCol < bBitmapOccupancyCols);
                    }
                    nRow++;
                } while (nRow < bBitmapOccupancyRows);
            }
        } else if (_stricmp(szTok, "entry_exit") == 0) {
            ParseEntryExitMaybe(pStream);
        } else if (_stricmp(szTok, "RMBSeq") == 0) {
            *pStream >> wRMBSeq;
        } else if (_stricmp(szTok, "ClosedFS") == 0) {
            *pStream >> wClosedFS;
        } else if (_stricmp(szTok, "EEReplayDelay") == 0) {
            *pStream >> lEEReplayDelay;
        } else if (_strnicmp(szTok, "MaxM", 4) == 0) {
            *pStream >> usValue;
            bSpawnVariance = (unsigned char)usValue;
            if ((unsigned char)usValue > 5) {
                bSpawnVariance = 5;
            }
        } else if (_stricmp(szTok, "LeisureDestination") == 0) {
            *pStream >> usValue;
            bCountedInReadyBigObjCount = (unsigned char)usValue;
        } else if (_stricmp(szTok, "MaxEmployees") == 0) {
            *pStream >> usValue;
            bMaxEmployees = (unsigned char)usValue;
            if ((unsigned char)usValue > 5) {
                bMaxEmployees = 5;
            }
        } else if (_stricmp(szTok, "PossibleEmployees") == 0) {
            short *pEntry = aPossibleEmployees;
            int i = 5;
            do {
                *pStream >> *pEntry;
                if ((unsigned char)TileKind_GetCategory(*pEntry) == 7 &&
                    *pEntry != -1 && *pEntry % 2 != 0) {
                    *pEntry = -1;
                }
                pEntry++;
                i--;
            } while (i != 0);
        } else if (_stricmp(szTok, "PossibleMinifigs") == 0) {
            short *pEntry = aPossibleMinifigs;
            int i = 5;
            do {
                *pStream >> *pEntry;
                if ((unsigned char)TileKind_GetCategory(*pEntry) == 7 &&
                    *pEntry != -1 && *pEntry % 2 != 0) {
                    *pEntry = -1;
                }
                if (*pEntry != -1) {
                    nMinifigCount++;
                }
                pEntry++;
                i--;
            } while (i != 0);
        } else if (_stricmp(szTok, "shifts") == 0) {
            pStream->getline(szTok, 0x104, '\n');
            // "openHour openMin closeHour closeMin" -- m_8 before m_4, twice. This operand
            // order is one of the two independent witnesses that pin TimeOfDayMaybe's
            // m_8=hour/m_4=minute assignment (see src/TimeOfDayMaybe.h).
            sscanf(szTok, "%ld %ld %ld %ld", &shiftOpen.m_8, &shiftOpen.m_4,
                   &shiftClose.m_8, &shiftClose.m_4);
        } else if (_stricmp(szTok, "FreeToRoam") == 0) {
            *pStream >> lFreeToRoamLeft >> lFreeToRoamTop;
            *pStream >> lFreeToRoamRight >> lFreeToRoamBottom;
        } else if (_stricmp(szTok, "ButtonVisible") == 0) {
            *pStream >> usValue;
            bButtonVisible = (unsigned char)usValue;
        } else if (_stricmp(szTok, "InsertSeq") == 0) {
            ParseSeqRecordMaybe(pStream, &lInsertSeqHeadMaybe);
        } else if (_stricmp(szTok, "MobileSeq") == 0) {
            ParseSeqRecordMaybe(pStream, &lMobileSeqHeadMaybe);
        } else if (_stricmp(szTok, "TotalVisits") == 0) {
            ParseSeqRecordMaybe(pStream, &lTotalVisitsHeadMaybe);
        } else {
            bResult = 0;
        }
        *pStream >> szTok;
    }

    if (_stricmp(szTok, "-9") != 0) {
        bResult = 0;
    }
    bFootprintHotspotEncodedMaybe = (bFootprintYSteps * 15 + bBitmapOccupancyRows) * 16;
    if (nMinifigCount == 0) {
        bSpawnVariance = 0;
    }
    return bResult;
}

// FUNCTION: LOCO 0x41efa0
// Obj0x4779e0::ParsePhysicalOccupancyMaybe -- the "physical_occupancy" keyword handler
// (Ghidra: BigObj_ParsePhysicalOccupancyMaybe). Reads the 3 footprint-dimension bytes
// (X/Y steps + layer count) into locals, stamps them, unconditionally zeroes the full
// 819-byte footprint-occupancy mask (13*9*7 capacity), then reads
// X*Y*layer bytes off the stream into the mask at [x*63 + y*7 + layer] (inner X stride 63,
// mid Y stride 7, outer layer stride 1 -- the fixed capacity strides, NOT the read counts).
unsigned char Obj0x4779e0::ParsePhysicalOccupancyMaybe(istream *pStream) { // TODO: sync (Ghidra: Obj0x4779e0::ParsePhysicalOccupancyMaybe -- the ParsePartial view is TU-local, see above)
    unsigned short usXSteps;
    unsigned short usYSteps;
    unsigned short usLayerCount;
    int nLayer;
    int nY;
    int nX;

    *pStream >> usXSteps >> usYSteps >> usLayerCount;
    bFootprintXSteps = (unsigned char)usXSteps;
    bFootprintYSteps = (unsigned char)usYSteps;
    bFootprintLayerCount = (unsigned char)usLayerCount;
    memset(aFootprintOccupancyMask, 0, sizeof(aFootprintOccupancyMask));

    nLayer = 0;
    if (bFootprintLayerCount > 0) {
        do {
            nY = 0;
            if (bFootprintYSteps > 0) {
                do {
                    nX = 0;
                    if (bFootprintXSteps > 0) {
                        do {
                            *pStream >> usXSteps;
                            aFootprintOccupancyMask[nX][nY][nLayer] = (unsigned char)usXSteps;
                            nX++;
                        } while (nX < bFootprintXSteps);
                    }
                    nY++;
                } while (nY < bFootprintYSteps);
            }
            nLayer++;
        } while (nLayer < bFootprintLayerCount);
    }
    return 1;
}

// FUNCTION: LOCO 0x41f0c0
// Obj0x4779e0::ParseEntryExitMaybe (0x41f0c0) -- the "entry_exit" keyword handler. Reads 4 ushort edge
// selectors, resets the whole 8-long entry/exit record (+0x5fc..+0x618) to -1, then fills
// each edge's pair from its selector: 0 leaves the pair at -1; the magic value (2 for
// edges 0/1, any of 1..3 for edges 2/3) derives the coordinate from the bitmap-occupancy
// grid dimensions (rows/cols * 32 / 4, rows/cols * 16 - 1, (rows - footprintY) * 16);
// any other value is stored verbatim. Returns 1.
// ⚠ THE CANARY FOR src/CursorDesc.h's DECLARATION DIAL -- if a header change is going to cost
// this repo an EXACT, it shows up HERE first. It was spent deliberately in v557b (EXACT at
// 3a52a30 -> DIFF(19) at identical length, -489 B) to give CursorDesc its real ctor, and
// RECOVERED in full in v557d without giving any of that back.
//
// The measured trail is the reusable part, because it refutes the obvious model (CODEGEN #168):
// adding Obj0x4779e0's ctor declaration was free and won these 489 B back; adding its dtor lost
// them again; adding four more parse-method declarations did nothing at all; adding BigObj's
// ctor/dtor/Load won them back for good. The dial is a THRESHOLD, not a per-declaration tariff,
// so a single declaration's local price is not evidence about the set it belongs to. If a future
// header change puts this function back into DIFF, try ADDING another real declaration before
// concluding anything.
unsigned char Obj0x4779e0::ParseEntryExitMaybe(istream *pStream) {
    unsigned short usEdgeA;
    unsigned short usEdgeB;
    unsigned short usEdgeC;
    unsigned short usEdgeD;

    *pStream >> usEdgeA >> usEdgeB >> usEdgeC >> usEdgeD;
    aEntryExitMaybe[0] = -1;
    aEntryExitMaybe[1] = -1;
    aEntryExitMaybe[2] = -1;
    aEntryExitMaybe[3] = -1;
    aEntryExitMaybe[4] = -1;
    aEntryExitMaybe[5] = -1;
    aEntryExitMaybe[6] = -1;
    aEntryExitMaybe[7] = -1;

    if (usEdgeA > 0) {
        aEntryExitMaybe[0] = 0;
        if (usEdgeA == 2) {
            aEntryExitMaybe[1] = bBitmapOccupancyRows * 32 / 4;
        } else {
            aEntryExitMaybe[1] = usEdgeA;
        }
    }
    if (usEdgeB > 0) {
        if (usEdgeB == 2) {
            aEntryExitMaybe[2] = bBitmapOccupancyCols * 32 / 4;
            aEntryExitMaybe[3] = bBitmapOccupancyRows * 16 - 1;
        } else {
            aEntryExitMaybe[2] = usEdgeB;
            aEntryExitMaybe[3] = bBitmapOccupancyRows * 16 - 1;
        }
    }
    if (usEdgeC > 0) {
        if (usEdgeC < 4) {
            aEntryExitMaybe[4] = bBitmapOccupancyCols * 16 - 1;
            aEntryExitMaybe[5] = bBitmapOccupancyRows * usEdgeC * 16 / 4;
        } else {
            aEntryExitMaybe[4] = bBitmapOccupancyCols * 16 - 1;
            aEntryExitMaybe[5] = usEdgeC;
        }
    }
    if (usEdgeD > 0) {
        if (usEdgeD < 4) {
            aEntryExitMaybe[6] = bBitmapOccupancyCols * usEdgeD * 16 / 4;
            aEntryExitMaybe[7] = (bBitmapOccupancyRows - bFootprintYSteps) * 16;
        } else {
            aEntryExitMaybe[6] = usEdgeD;
            aEntryExitMaybe[7] = (bBitmapOccupancyRows - bFootprintYSteps) * 16;
        }
    }
    return 1;
}

// FUNCTION: LOCO 0x41f2b0
// Obj0x4779e0::ParseSeqRecordMaybe (0x41f2b0) -- the shared InsertSeq/MobileSeq/TotalVisits keyword-record
// parser. Reads the record's lead ulong + element count (capped at 0x2d), allocates the
// count-long values array, fills it, then the fixed scalar tail: a discarded string token,
// long/float pairs, a char (stored sign-extended at +0x28), 2 more longs. Afterwards
// re-validates the +0xc long's tile category (2/4/0xd/0xc keep it, anything else positive
// -> +0x14 = -1) and the +0x14 long's (category 7 keeps it, else -1). NULL record -> 0,
// else 1. Never touches `this` (Ghidra types it __stdcall; every call site sets up ecx --
// it was written as a member).
unsigned char Obj0x4779e0::ParseSeqRecordMaybe(istream *pStream, unsigned long *pRec) { // TODO: sync (Ghidra: Obj0x4779e0::ParseSeqRecordMaybe -- the ParsePartial view is TU-local, see above)
    unsigned long i;
    char ch;
    char szTok[264];

    if (pRec == NULL) {
        return 0;
    }
    *pStream >> pRec[0] >> pRec[1];
    if (pRec[1] > 0 && pRec[1] < 0x2d) {
        pRec[2] = (unsigned long)new long[pRec[1]];
        if (pRec[2] != 0) {
            i = 0;
            if (pRec[1] > 0) {
                do {
                    *pStream >> ((long *)pRec[2])[i];
                    i++;
                } while (i < pRec[1]);
            }
        } else {
            pRec[1] = 0;
        }
    } else {
        pRec[1] = 0;
    }
    *pStream >> szTok;
    *pStream >> (long &)pRec[3];
    *pStream >> (short &)pRec[4];
    *pStream >> (long &)pRec[5];
    *pStream >> (short &)pRec[6];
    *pStream >> (long &)pRec[7];
    *pStream >> (long &)pRec[8];
    *pStream >> (short &)pRec[9];
    *pStream >> ch;
    *pStream >> (long &)pRec[11];
    *pStream >> (long &)pRec[12];
    pRec[10] = ch;
    if ((long)pRec[3] > 0 && (unsigned char)TileKind_GetCategory(pRec[3]) != 2 &&
        (unsigned char)TileKind_GetCategory(pRec[3]) != 4 &&
        (unsigned char)TileKind_GetCategory(pRec[3]) != 0xd &&
        (unsigned char)TileKind_GetCategory(pRec[3]) != 0xc) {
        pRec[5] = -1;
    }
    if ((long)pRec[5] > 0 && (unsigned char)TileKind_GetCategory(pRec[5]) != 7) {
        pRec[5] = -1;
    }
    return 1;
}

// FUNCTION: LOCO 0x41f430
// "Is this kind a PLAIN RUN?" -- the predicate WorldBoardMaybe's four track-graph walkers use to
// decide which tiles to step THROUGH on the way to the next junction, rather than give a
// TrackGraphNode of their own. True for a track-family piece (categoryByte 3) whose m_type0x63a
// is a straight or a curve, and for the two plain path pieces (categoryByte 0xc, resourceId
// 0x3001/0x3002); everything else -- points/switches, crossings, buildings, decor -- is false.
// Sits immediately after ParseSeqRecordMaybe in .text, which is what puts it in this TU even
// though its siblings on BigObj live in src/CursorDesc.cpp.
unsigned char BigObj::IsPlainRunMaybe() {
    if (categoryByte != 3) {
        if (categoryByte != 12) {
            return 0;
        }
        if (resourceId != 0x3001 && resourceId != 0x3002) {
            return 0;
        }
    } else {
        if (!IsType0x63aInSetE() && !IsType0x63aInSet10()) {
            return 0;
        }
    }
    return 1;
}

// 0x34-byte span of one InsertSeq/MobileSeq/TotalVisits keyword record in the Obj0x4779e0
// field block (head + count + paValues + tail) -- a named record STRUCT in CursorDesc.h
// rotates DPlaySessionMgr.cpp's TU (v331 bisect), so the records stay flattened scalars
// there and only this TU-local span type gives Load's record-clear memsets a sizeof.
struct Obj0x4779e0SeqRecordSpan {
    unsigned char raw[0x34];
};

// FUNCTION: LOCO 0x41e6e0 // EFFECTIVE MATCH -- 208/213 insns structurally matching,
// byte_diff 75/777 (asmscore 85235, align=80 reg_pen=47 identity_miss=46). Whole-function
// structure verified against the original (init sweep, RF-archive-then-loose-file fallback,
// dual ParseTokenField, hotspot seed). Residual is 3 tie classes: (1) the hotspot guard's
// 11-byte branchy bool materialization (mov eax,1/xor eax,eax/cmp al,bl) that this compile
// folds into two direct jne branches -- 9 guard phrasings tried (plain &&, bool/int temp,
// ternary 1:0, true/false assignment, & 1, !x&&!y, sete forms), ALL fold, see docs/PARKED.md;
// (2) the istrstream delete's vbase-load shape (orig lea+reload vs this compile's add, -2B);
// (3) pervasive eax/ecx/edx reg-role ties + 2 scheduling swaps in the archive/fallback blocks.
// Obj0x4779e0::LoadMaybe (vtable slot +0x10, the Load override; Ghidra:
// Obj0x4779e0::LoadMaybe) -- the full per-kind .dat loader. Defaults every owned field
// (minifig/employee tables to -1, the 3 seq records zeroed with their 3 tail longs at -1,
// entry/exit record zeroed, FreeToRoam rect emptied), then builds "<prefix><name>.dat"/
// "<prefix><name>.bmp" paths and tries the RF archive first (istrstream over the loaded
// resource), falling back to a loose ifstream (ios::nocreate); whichever stream parses is
// fed through this tier's virtual ParseTokenField, then CursorDesc's own. Finally seeds
// the cursor hotspot from the bitmap-occupancy grid when unset ((cols/2)*16, rows*16-16).
void Obj0x4779e0::LoadMaybe(unsigned int kindIdUnused, char *pszName) {
    int nSize;
    void *pRfBuf;
    istrstream *pRfStream;
    ifstream fileStream;
    char szDatPath[264];
    char szRfName[264];

    bMaxEmployees = 0;
    bSpawnVariance = 0;
    memset(aPossibleMinifigs, 0xff, sizeof(aPossibleMinifigs));
    memset(aPossibleEmployees, 0xff, sizeof(aPossibleEmployees));
    bFootprintXSteps = 0;
    bFootprintYSteps = 0;
    bFootprintLayerCount = 0;
    wRMBSeq = 0;
    wUnk0x532Maybe = 0;
    wClosedFS = -1;
    lEEReplayDelay = 0;
    memset(&lInsertSeqHeadMaybe, 0, sizeof(Obj0x4779e0SeqRecordSpan));
    lInsertSeqUnk0x568Maybe = -1;
    lInsertSeqUnk0x570Maybe = -1;
    lInsertSeqUnk0x57cMaybe = -1;
    memset(&lMobileSeqHeadMaybe, 0, sizeof(Obj0x4779e0SeqRecordSpan));
    lMobileSeqUnk0x59cMaybe = -1;
    lMobileSeqUnk0x5a4Maybe = -1;
    lMobileSeqUnk0x5b0Maybe = -1;
    memset(&lTotalVisitsHeadMaybe, 0, sizeof(Obj0x4779e0SeqRecordSpan));
    lTotalVisitsUnk0x5d0Maybe = -1;
    lTotalVisitsUnk0x5d8Maybe = -1;
    lTotalVisitsUnk0x5e4Maybe = -1;
    memset(aEntryExitMaybe, 0, sizeof(aEntryExitMaybe));
    SetRectEmpty((RECT *)&lFreeToRoamLeft);
    bCountedInReadyBigObjCount = 0;
    bLoadOkFlag = 0;
    if (pszName != NULL) {
        sprintf(szDatPath, "%s%s.dat", g_pInstallPathPrefix, pszName);
        sprintf(szBmpPath, "%s%s.bmp", g_pInstallPathPrefix, pszName);
        bool bHaveArchive = g_RFIndex.pFile != NULL;
        if (bHaveArchive) {
            sprintf(szRfName, "%s.dat", pszName);
            pRfBuf = g_RFIndex.LoadResource((const unsigned char *)szRfName, &nSize);
            if (pRfBuf != NULL) {
                pRfStream = new istrstream((char *)pRfBuf, nSize);
                if (pRfStream != NULL) {
                    bLoadOkFlag = ParseTokenField(pRfStream);
                    bLoadOkFlag = (bLoadOkFlag != 0 && CursorDesc::ParseTokenField(pRfStream) != 0) ? 1 : 0;
                    delete pRfStream;
                }
                _free(pRfBuf);
            }
        }
    }
    if (bLoadOkFlag == 0) {
        fileStream.open(szDatPath, ios::nocreate);
        if (fileStream.is_open()) {
            bLoadOkFlag = ParseTokenField(&fileStream);
            bLoadOkFlag = (bLoadOkFlag != 0 && CursorDesc::ParseTokenField(&fileStream) != 0) ? 1 : 0;
            fileStream.close();
        }
    }
    if (hotspotX == 0 && hotspotY == 0) {
        hotspotX = (unsigned short)(bBitmapOccupancyCols >> 1) << 4;
        hotspotY = bBitmapOccupancyRows * 16 - 16;
    }
}

// FUNCTION: LOCO 0x41e570
// Obj0x4779e0::Obj0x4779e0 (Ghidra: Obj0x4779e0::Obj0x4779e0) -- constructs the CursorDesc
// base (arg1, 0, 1), then the two TimeOfDayMaybe "shifts" embeds
// (+0x534, +0x548 -- compiler init chain, EH states 1/2), stamps the vtable, NULLs the 3
// owned keyword-record value arrays, and runs the full .dat LoadMaybe(arg1, arg2).
Obj0x4779e0::Obj0x4779e0(unsigned int kindId, char *pszName) : CursorDesc(kindId, NULL, 1) {
    paInsertSeqValues = NULL;
    paMobileSeqValues = NULL;
    paTotalVisitsValues = NULL;
    LoadMaybe(kindId, pszName);
}
