// ScopedTimestampMaybe -- tiny polymorphic timestamped-record class (vtable 0x4779f4).
// Its ctor (0x41f480, transcribed 2026-07-29 in src/ScriptEventLoader.cpp) stores _time() at +4
// and zeroes +8/+0x10 (size 0x14). Only ever referenced from an orphan code block at
// 0x45c655..0x45c675
// (not inside any Ghidra-defined function -- construct, then immediately destruct, so
// likely a global/static scope guard or an atexit-registered static). Owner subsystem
// genuinely unidentified; the bare vtable-dtor stub (0x41f4d0) is transcribed EXACT and the
// auto-generated ??_G (0x41f4b0) is EFFECTIVE-parked (inline-into-??_G class, see below).
// Moved out of src/phase2_probe2.cpp 2026-07-22 (v322, was VtblStub0x41f4d0).
//
// ⚠ OWNER IDENTIFIED 2026-07-29 (v494): this "orphan class" is the ScriptEventLoader
// singleton's class. The static object is DAT_004a99b0 (static-init thunk 0x45c650 calls ctor
// 0x41f480, the atexit thunk 0x45c670 jmps to this dtor 0x41f4d0), its +0x4 field IS
// g_dwGameTick (DAT_004a99b4 -- _time()d here and re-_time()d by the timer proc at 0x45c3c0),
// +0x8/+0xc are the two ee.ini script-record lists, +0x10 the easter-egg count. The class's 15
// other methods (0x41f4e0..0x4202b0) are transcribed in src/ScriptEventLoader.cpp under the
// name `ScriptEventLoader` -- which makes THIS file's model the same class's ctor/dtor home,
// and the "ScopedTimestampMaybe" name obsolete pending a measured unification of the two TUs
// (this file's EXACT is not to be rotated casually). The vtable oddity noted at the top --
// 0x4779f4's slot run is SplashWnd_Vtbl's (0x4779f8) entire table with one dword prepended --
// is still unexplained.

class ScopedTimestampMaybe {
public:
    virtual ~ScopedTimestampMaybe(); // vtable slot 0 = the ??_G scalar deleting dtor (0x41f4b0)
    virtual void Method0(); // slot 1 -- the real body (0x4203a0) is unread
};

// FUNCTION: LOCO 0x41f4b0 (??_GScopedTimestampMaybe scalar dtor)
// EFFECTIVE MATCH (v333): DIFF(22)/30B -- the original INLINES the trivial dtor body into
// ??_G (vtable store inside the flag test, then the delete); VC5 emits a CALL to the
// out-of-line ??1 below instead. Same class as ??_GThreadWrapper (v322, docs/PARKED.md):
// moving the dtor in-class reproduces the inline but cl then drops BOTH COMDATs here
// (nothing else in the TU forces emission -- vtable slot 0 is ??_G itself), orphaning the
// 0x41f4d0 marker; the original's standalone ??1 survives because the orphan block's TU
// (0x45c655..0x45c675) calls it directly. Out-of-line form kept.
// Auto-generated by the virtual dtor below -- this COMDAT has no source line of its own.

// FUNCTION: LOCO 0x41f4d0
ScopedTimestampMaybe::~ScopedTimestampMaybe() {}  // TODO: sync
